import type { Adjective } from "./types";

/**
 * stem = lemma minus its ending (dobry -> dobr, tani -> tan, drogi -> drog).
 * virilePl = masculine-personal nominative plural, the one slot rules cannot
 * derive reliably because of consonant alternations (dobry -> dobrzy).
 * fits = only pair with nouns carrying one of these tags.
 */
export const ADJECTIVES: Adjective[] = [
  { lemma: "dobry", en: "good", stem: "dobr", type: "hard", virilePl: "dobrzy" },
  { lemma: "nowy", en: "new", stem: "now", type: "hard", virilePl: "nowi" },
  { lemma: "stary", en: "old", stem: "star", type: "hard", virilePl: "starzy" },
  { lemma: "mały", en: "small", stem: "mał", type: "hard", virilePl: "mali" },
  { lemma: "duży", en: "big", stem: "duż", type: "hard", virilePl: "duzi" },
  { lemma: "ładny", en: "pretty", stem: "ładn", type: "hard", virilePl: "ładni" },
  { lemma: "ciekawy", en: "interesting", stem: "ciekaw", type: "hard", virilePl: "ciekawi" },
  { lemma: "ważny", en: "important", stem: "ważn", type: "hard", virilePl: "ważni" },
  { lemma: "ulubiony", en: "favourite", stem: "ulubion", type: "hard", virilePl: "ulubieni" },
  { lemma: "znany", en: "well-known", stem: "znan", type: "hard", virilePl: "znani" },
  { lemma: "czarny", en: "black", stem: "czarn", type: "hard", virilePl: "czarni" ,
    fits: ["animal", "object", "vehicle", "food", "drink", "text", "surface", "placeIn"] },
  { lemma: "biały", en: "white", stem: "biał", type: "hard", virilePl: "biali" ,
    fits: ["animal", "object", "vehicle", "food", "drink", "text", "surface", "placeIn"] },
  { lemma: "zielony", en: "green", stem: "zielon", type: "hard", virilePl: "zieloni" ,
    fits: ["animal", "object", "vehicle", "food", "drink", "text", "surface", "placeIn"] },
  { lemma: "czerwony", en: "red", stem: "czerwon", type: "hard", virilePl: "czerwoni" ,
    fits: ["animal", "object", "vehicle", "food", "drink", "text", "surface", "placeIn"] },
  { lemma: "niebieski", en: "blue", stem: "niebiesk", type: "velar", virilePl: "niebiescy" ,
    fits: ["animal", "object", "vehicle", "food", "drink", "text", "surface", "placeIn"] },
  { lemma: "polski", en: "Polish", stem: "polsk", type: "velar", virilePl: "polscy" },
  { lemma: "wysoki", en: "tall", stem: "wysok", type: "velar", virilePl: "wysocy" },
  { lemma: "drogi", en: "expensive", stem: "drog", type: "velar", virilePl: "drodzy",
    fits: ["object", "vehicle", "food", "drink", "text", "placeIn"] },
  { lemma: "tani", en: "cheap", stem: "tan", type: "soft", virilePl: "tani",
    fits: ["object", "vehicle", "food", "drink", "text", "placeIn"] },
  { lemma: "głupi", en: "silly", stem: "głup", type: "soft", virilePl: "głupi",
    fits: ["person", "profession", "animal", "text", "abstract"] },
  { lemma: "młody", en: "young", stem: "młod", type: "hard", virilePl: "młodzi",
    fits: ["person", "profession", "animal"] },
  { lemma: "mądry", en: "wise", stem: "mądr", type: "hard", virilePl: "mądrzy",
    fits: ["person", "profession", "animal", "text"] },
  { lemma: "miły", en: "nice", stem: "mił", type: "hard", virilePl: "mili",
    fits: ["person", "profession", "animal"] },
  { lemma: "wesoły", en: "cheerful", stem: "wesoł", type: "hard", virilePl: "weseli",
    fits: ["person", "profession", "animal"] },
  { lemma: "smutny", en: "sad", stem: "smutn", type: "hard", virilePl: "smutni",
    fits: ["person", "profession", "animal", "text", "abstract"] },
  { lemma: "chory", en: "ill", stem: "chor", type: "hard", virilePl: "chorzy",
    fits: ["person", "profession", "animal"] },
  { lemma: "smaczny", en: "tasty", stem: "smaczn", type: "hard", virilePl: "smaczni",
    fits: ["food", "drink"] },
  { lemma: "zimny", en: "cold", stem: "zimn", type: "hard", virilePl: "zimni",
    fits: ["food", "drink", "object", "placeIn"] },
  { lemma: "gorący", en: "hot", stem: "gorąc", type: "hard", virilePl: "gorący",
    fits: ["food", "drink", "object"] },
  { lemma: "szybki", en: "fast", stem: "szybk", type: "velar", virilePl: "szybcy",
    fits: ["vehicle", "animal", "object"] },
  { lemma: "wygodny", en: "comfortable", stem: "wygodn", type: "hard", virilePl: "wygodni",
    fits: ["object", "vehicle", "placeIn", "surface"] },
  { lemma: "trudny", en: "difficult", stem: "trudn", type: "hard", virilePl: "trudni",
    fits: ["text", "abstract"] },
];
