import type { Case, Forms, Gender, GramNumber, Noun, Tag } from "./types";

type Row = [string, string, string, string, string, string, string];

/** Row order: nom, gen, dat, acc, ins, loc, voc. */
function forms(r: Row): Forms {
  return { nom: r[0], gen: r[1], dat: r[2], acc: r[3], ins: r[4], loc: r[5], voc: r[6] };
}

function n(
  lemma: string,
  en: string,
  enPl: string,
  gender: Gender,
  tags: Tag[],
  sg: Row,
  pl?: Row,
  extra?: Partial<Pick<Noun, "mass" | "noPlural" | "alt">>,
): Noun {
  return {
    lemma,
    en,
    enPl,
    gender,
    tags,
    sg: forms(sg),
    pl: pl ? forms(pl) : undefined,
    ...extra,
  };
}

/**
 * Every accepted spelling of one cell of a noun's table, primary form first.
 * Empty when that number has no table at all (mleko, muzyka...).
 */
export function nounVariants(noun: Noun, number: GramNumber, kase: Case): string[] {
  const table = number === "pl" ? noun.pl : noun.sg;
  if (!table) return [];
  return [table[kase], ...(noun.alt?.[`${number}.${kase}`] ?? [])];
}

export const NOUNS: Noun[] = [
  // ---- masculine personal ------------------------------------------------
  n("student", "student", "students", "mPers", ["person", "profession"],
    ["student", "studenta", "studentowi", "studenta", "studentem", "studencie", "studencie"],
    ["studenci", "studentów", "studentom", "studentów", "studentami", "studentach", "studenci"]),
  n("nauczyciel", "teacher", "teachers", "mPers", ["person", "profession"],
    ["nauczyciel", "nauczyciela", "nauczycielowi", "nauczyciela", "nauczycielem", "nauczycielu", "nauczycielu"],
    ["nauczyciele", "nauczycieli", "nauczycielom", "nauczycieli", "nauczycielami", "nauczycielach", "nauczyciele"]),
  n("lekarz", "doctor", "doctors", "mPers", ["person", "profession"],
    ["lekarz", "lekarza", "lekarzowi", "lekarza", "lekarzem", "lekarzu", "lekarzu"],
    ["lekarze", "lekarzy", "lekarzom", "lekarzy", "lekarzami", "lekarzach", "lekarze"]),
  n("pisarz", "writer", "writers", "mPers", ["person", "profession"],
    ["pisarz", "pisarza", "pisarzowi", "pisarza", "pisarzem", "pisarzu", "pisarzu"],
    ["pisarze", "pisarzy", "pisarzom", "pisarzy", "pisarzami", "pisarzach", "pisarze"]),
  n("dentysta", "dentist", "dentists", "mPers", ["person", "profession"],
    ["dentysta", "dentysty", "dentyście", "dentystę", "dentystą", "dentyście", "dentysto"],
    ["dentyści", "dentystów", "dentystom", "dentystów", "dentystami", "dentystach", "dentyści"]),
  n("brat", "brother", "brothers", "mPers", ["person"],
    ["brat", "brata", "bratu", "brata", "bratem", "bracie", "bracie"],
    ["bracia", "braci", "braciom", "braci", "braćmi", "braciach", "bracia"]),
  n("ojciec", "father", "fathers", "mPers", ["person"],
    ["ojciec", "ojca", "ojcu", "ojca", "ojcem", "ojcu", "ojcze"],
    ["ojcowie", "ojców", "ojcom", "ojców", "ojcami", "ojcach", "ojcowie"]),
  n("syn", "son", "sons", "mPers", ["person"],
    ["syn", "syna", "synowi", "syna", "synem", "synu", "synu"],
    ["synowie", "synów", "synom", "synów", "synami", "synach", "synowie"]),
  n("mąż", "husband", "husbands", "mPers", ["person"],
    ["mąż", "męża", "mężowi", "męża", "mężem", "mężu", "mężu"],
    ["mężowie", "mężów", "mężom", "mężów", "mężami", "mężach", "mężowie"]),
  n("dziadek", "grandfather", "grandfathers", "mPers", ["person"],
    ["dziadek", "dziadka", "dziadkowi", "dziadka", "dziadkiem", "dziadku", "dziadku"],
    ["dziadkowie", "dziadków", "dziadkom", "dziadków", "dziadkami", "dziadkach", "dziadkowie"]),
  n("chłopiec", "boy", "boys", "mPers", ["person"],
    ["chłopiec", "chłopca", "chłopcu", "chłopca", "chłopcem", "chłopcu", "chłopcze"],
    ["chłopcy", "chłopców", "chłopcom", "chłopców", "chłopcami", "chłopcach", "chłopcy"]),
  n("mężczyzna", "man", "men", "mPers", ["person"],
    ["mężczyzna", "mężczyzny", "mężczyźnie", "mężczyznę", "mężczyzną", "mężczyźnie", "mężczyzno"],
    ["mężczyźni", "mężczyzn", "mężczyznom", "mężczyzn", "mężczyznami", "mężczyznach", "mężczyźni"]),
  n("kolega", "friend", "friends", "mPers", ["person"],
    ["kolega", "kolegi", "koledze", "kolegę", "kolegą", "koledze", "kolego"],
    ["koledzy", "kolegów", "kolegom", "kolegów", "kolegami", "kolegach", "koledzy"]),
  n("przyjaciel", "close friend", "close friends", "mPers", ["person"],
    ["przyjaciel", "przyjaciela", "przyjacielowi", "przyjaciela", "przyjacielem", "przyjacielu", "przyjacielu"],
    ["przyjaciele", "przyjaciół", "przyjaciołom", "przyjaciół", "przyjaciółmi", "przyjaciołach", "przyjaciele"]),
  n("sąsiad", "neighbour", "neighbours", "mPers", ["person"],
    ["sąsiad", "sąsiada", "sąsiadowi", "sąsiada", "sąsiadem", "sąsiedzie", "sąsiedzie"],
    ["sąsiedzi", "sąsiadów", "sąsiadom", "sąsiadów", "sąsiadami", "sąsiadach", "sąsiedzi"]),
  n("pan", "gentleman", "gentlemen", "mPers", ["person"],
    ["pan", "pana", "panu", "pana", "panem", "panu", "panie"],
    ["panowie", "panów", "panom", "panów", "panami", "panach", "panowie"]),

  // ---- masculine animate -------------------------------------------------
  n("kot", "cat", "cats", "mAnim", ["animal"],
    ["kot", "kota", "kotu", "kota", "kotem", "kocie", "kocie"],
    ["koty", "kotów", "kotom", "koty", "kotami", "kotach", "koty"]),
  n("pies", "dog", "dogs", "mAnim", ["animal"],
    ["pies", "psa", "psu", "psa", "psem", "psie", "psie"],
    ["psy", "psów", "psom", "psy", "psami", "psach", "psy"]),
  n("koń", "horse", "horses", "mAnim", ["animal"],
    ["koń", "konia", "koniowi", "konia", "koniem", "koniu", "koniu"],
    ["konie", "koni", "koniom", "konie", "końmi", "koniach", "konie"]),
  n("ptak", "bird", "birds", "mAnim", ["animal"],
    ["ptak", "ptaka", "ptakowi", "ptaka", "ptakiem", "ptaku", "ptaku"],
    ["ptaki", "ptaków", "ptakom", "ptaki", "ptakami", "ptakach", "ptaki"]),
  n("słoń", "elephant", "elephants", "mAnim", ["animal"],
    ["słoń", "słonia", "słoniowi", "słonia", "słoniem", "słoniu", "słoniu"],
    ["słonie", "słoni", "słoniom", "słonie", "słoniami", "słoniach", "słonie"]),

  // ---- masculine inanimate ----------------------------------------------
  n("stół", "table", "tables", "mInanim", ["object", "surface"],
    ["stół", "stołu", "stołowi", "stół", "stołem", "stole", "stole"],
    ["stoły", "stołów", "stołom", "stoły", "stołami", "stołach", "stoły"]),
  n("dom", "house", "houses", "mInanim", ["placeIn", "placeTo", "object"],
    ["dom", "domu", "domowi", "dom", "domem", "domu", "domu"],
    ["domy", "domów", "domom", "domy", "domami", "domach", "domy"]),
  n("samochód", "car", "cars", "mInanim", ["vehicle", "object"],
    ["samochód", "samochodu", "samochodowi", "samochód", "samochodem", "samochodzie", "samochodzie"],
    ["samochody", "samochodów", "samochodom", "samochody", "samochodami", "samochodach", "samochody"]),
  n("sklep", "shop", "shops", "mInanim", ["placeIn", "placeTo"],
    ["sklep", "sklepu", "sklepowi", "sklep", "sklepem", "sklepie", "sklepie"],
    ["sklepy", "sklepów", "sklepom", "sklepy", "sklepami", "sklepach", "sklepy"]),
  n("komputer", "computer", "computers", "mInanim", ["object"],
    ["komputer", "komputera", "komputerowi", "komputer", "komputerem", "komputerze", "komputerze"],
    ["komputery", "komputerów", "komputerom", "komputery", "komputerami", "komputerach", "komputery"]),
  n("telefon", "phone", "phones", "mInanim", ["object"],
    ["telefon", "telefonu", "telefonowi", "telefon", "telefonem", "telefonie", "telefonie"],
    ["telefony", "telefonów", "telefonom", "telefony", "telefonami", "telefonach", "telefony"]),
  n("długopis", "pen", "pens", "mInanim", ["object"],
    ["długopis", "długopisu", "długopisowi", "długopis", "długopisem", "długopisie", "długopisie"],
    ["długopisy", "długopisów", "długopisom", "długopisy", "długopisami", "długopisach", "długopisy"]),
  n("nóż", "knife", "knives", "mInanim", ["object"],
    ["nóż", "noża", "nożowi", "nóż", "nożem", "nożu", "nożu"],
    ["noże", "noży", "nożom", "noże", "nożami", "nożach", "noże"]),
  n("chleb", "bread", "loaves of bread", "mInanim", ["food"],
    ["chleb", "chleba", "chlebowi", "chleb", "chlebem", "chlebie", "chlebie"],
    ["chleby", "chlebów", "chlebom", "chleby", "chlebami", "chlebach", "chleby"],
    { mass: true }),
  n("ser", "cheese", "cheeses", "mInanim", ["food"],
    ["ser", "sera", "serowi", "ser", "serem", "serze", "serze"],
    ["sery", "serów", "serom", "sery", "serami", "serach", "sery"],
    { mass: true }),
  n("sok", "juice", "juices", "mInanim", ["drink"],
    ["sok", "soku", "sokowi", "sok", "sokiem", "soku", "soku"],
    ["soki", "soków", "sokom", "soki", "sokami", "sokach", "soki"],
    { mass: true }),
  n("park", "park", "parks", "mInanim", ["placeIn", "placeTo"],
    ["park", "parku", "parkowi", "park", "parkiem", "parku", "parku"],
    ["parki", "parków", "parkom", "parki", "parkami", "parkach", "parki"]),
  n("hotel", "hotel", "hotels", "mInanim", ["placeIn", "placeTo"],
    ["hotel", "hotelu", "hotelowi", "hotel", "hotelem", "hotelu", "hotelu"],
    ["hotele", "hoteli", "hotelom", "hotele", "hotelami", "hotelach", "hotele"]),
  n("ogród", "garden", "gardens", "mInanim", ["placeIn", "placeTo"],
    ["ogród", "ogrodu", "ogrodowi", "ogród", "ogrodem", "ogrodzie", "ogrodzie"],
    ["ogrody", "ogrodów", "ogrodom", "ogrody", "ogrodami", "ogrodach", "ogrody"]),
  n("kościół", "church", "churches", "mInanim", ["placeIn", "placeTo"],
    ["kościół", "kościoła", "kościołowi", "kościół", "kościołem", "kościele", "kościele"],
    ["kościoły", "kościołów", "kościołom", "kościoły", "kościołami", "kościołach", "kościoły"]),
  n("pokój", "room", "rooms", "mInanim", ["placeIn"],
    ["pokój", "pokoju", "pokojowi", "pokój", "pokojem", "pokoju", "pokoju"],
    ["pokoje", "pokoi", "pokojom", "pokoje", "pokojami", "pokojach", "pokoje"],
    { alt: { "pl.gen": ["pokojów"] } }),
  n("list", "letter", "letters", "mInanim", ["text", "object"],
    ["list", "listu", "listowi", "list", "listem", "liście", "liście"],
    ["listy", "listów", "listom", "listy", "listami", "listach", "listy"]),
  n("kwiat", "flower", "flowers", "mInanim", ["object"],
    ["kwiat", "kwiatu", "kwiatowi", "kwiat", "kwiatem", "kwiecie", "kwiecie"],
    ["kwiaty", "kwiatów", "kwiatom", "kwiaty", "kwiatami", "kwiatach", "kwiaty"]),
  n("samolot", "plane", "planes", "mInanim", ["vehicle", "object"],
    ["samolot", "samolotu", "samolotowi", "samolot", "samolotem", "samolocie", "samolocie"],
    ["samoloty", "samolotów", "samolotom", "samoloty", "samolotami", "samolotach", "samoloty"]),
  n("tydzień", "week", "weeks", "mInanim", ["abstract"],
    ["tydzień", "tygodnia", "tygodniowi", "tydzień", "tygodniem", "tygodniu", "tygodniu"],
    ["tygodnie", "tygodni", "tygodniom", "tygodnie", "tygodniami", "tygodniach", "tygodnie"]),

  n("pociąg", "train", "trains", "mInanim", ["vehicle", "object"],
    ["pociąg", "pociągu", "pociągowi", "pociąg", "pociągiem", "pociągu", "pociągu"],
    ["pociągi", "pociągów", "pociągom", "pociągi", "pociągami", "pociągach", "pociągi"]),
  n("autobus", "bus", "buses", "mInanim", ["vehicle", "object"],
    ["autobus", "autobusu", "autobusowi", "autobus", "autobusem", "autobusie", "autobusie"],
    ["autobusy", "autobusów", "autobusom", "autobusy", "autobusami", "autobusach", "autobusy"]),
  n("rower", "bicycle", "bicycles", "mInanim", ["vehicle", "object"],
    ["rower", "roweru", "rowerowi", "rower", "rowerem", "rowerze", "rowerze"],
    ["rowery", "rowerów", "rowerom", "rowery", "rowerami", "rowerach", "rowery"]),
  n("łóżko", "bed", "beds", "n", ["object", "surface"],
    ["łóżko", "łóżka", "łóżku", "łóżko", "łóżkiem", "łóżku", "łóżko"],
    ["łóżka", "łóżek", "łóżkom", "łóżka", "łóżkami", "łóżkach", "łóżka"]),
  n("podłoga", "floor", "floors", "f", ["object", "surface"],
    ["podłoga", "podłogi", "podłodze", "podłogę", "podłogą", "podłodze", "podłogo"],
    ["podłogi", "podłóg", "podłogom", "podłogi", "podłogami", "podłogach", "podłogi"]),

  // ---- feminine ----------------------------------------------------------
  n("kobieta", "woman", "women", "f", ["person"],
    ["kobieta", "kobiety", "kobiecie", "kobietę", "kobietą", "kobiecie", "kobieto"],
    ["kobiety", "kobiet", "kobietom", "kobiety", "kobietami", "kobietach", "kobiety"]),
  n("dziewczyna", "girl", "girls", "f", ["person"],
    ["dziewczyna", "dziewczyny", "dziewczynie", "dziewczynę", "dziewczyną", "dziewczynie", "dziewczyno"],
    ["dziewczyny", "dziewczyn", "dziewczynom", "dziewczyny", "dziewczynami", "dziewczynach", "dziewczyny"]),
  n("siostra", "sister", "sisters", "f", ["person"],
    ["siostra", "siostry", "siostrze", "siostrę", "siostrą", "siostrze", "siostro"],
    ["siostry", "sióstr", "siostrom", "siostry", "siostrami", "siostrach", "siostry"]),
  n("matka", "mother", "mothers", "f", ["person"],
    ["matka", "matki", "matce", "matkę", "matką", "matce", "matko"],
    ["matki", "matek", "matkom", "matki", "matkami", "matkach", "matki"]),
  n("córka", "daughter", "daughters", "f", ["person"],
    ["córka", "córki", "córce", "córkę", "córką", "córce", "córko"],
    ["córki", "córek", "córkom", "córki", "córkami", "córkach", "córki"]),
  n("żona", "wife", "wives", "f", ["person"],
    ["żona", "żony", "żonie", "żonę", "żoną", "żonie", "żono"],
    ["żony", "żon", "żonom", "żony", "żonami", "żonach", "żony"]),
  n("babcia", "grandmother", "grandmothers", "f", ["person"],
    ["babcia", "babci", "babci", "babcię", "babcią", "babci", "babciu"],
    ["babcie", "babć", "babciom", "babcie", "babciami", "babciach", "babcie"]),
  n("pani", "lady", "ladies", "f", ["person"],
    ["pani", "pani", "pani", "panią", "panią", "pani", "pani"],
    ["panie", "pań", "paniom", "panie", "paniami", "paniach", "panie"]),
  n("rodzina", "family", "families", "f", ["person", "abstract"],
    ["rodzina", "rodziny", "rodzinie", "rodzinę", "rodziną", "rodzinie", "rodzino"],
    ["rodziny", "rodzin", "rodzinom", "rodziny", "rodzinami", "rodzinach", "rodziny"]),
  n("książka", "book", "books", "f", ["text", "object"],
    ["książka", "książki", "książce", "książkę", "książką", "książce", "książko"],
    ["książki", "książek", "książkom", "książki", "książkami", "książkach", "książki"]),
  n("gazeta", "newspaper", "newspapers", "f", ["text", "object"],
    ["gazeta", "gazety", "gazecie", "gazetę", "gazetą", "gazecie", "gazeto"],
    ["gazety", "gazet", "gazetom", "gazety", "gazetami", "gazetach", "gazety"]),
  n("woda", "water", "waters", "f", ["drink"],
    ["woda", "wody", "wodzie", "wodę", "wodą", "wodzie", "wodo"],
    ["wody", "wód", "wodom", "wody", "wodami", "wodach", "wody"],
    { mass: true }),
  n("herbata", "tea", "teas", "f", ["drink"],
    ["herbata", "herbaty", "herbacie", "herbatę", "herbatą", "herbacie", "herbato"],
    ["herbaty", "herbat", "herbatom", "herbaty", "herbatami", "herbatach", "herbaty"],
    { mass: true }),
  n("kawa", "coffee", "coffees", "f", ["drink"],
    ["kawa", "kawy", "kawie", "kawę", "kawą", "kawie", "kawo"],
    ["kawy", "kaw", "kawom", "kawy", "kawami", "kawach", "kawy"],
    { mass: true }),
  n("zupa", "soup", "soups", "f", ["food"],
    ["zupa", "zupy", "zupie", "zupę", "zupą", "zupie", "zupo"],
    ["zupy", "zup", "zupom", "zupy", "zupami", "zupach", "zupy"]),
  n("szkoła", "school", "schools", "f", ["placeIn", "placeTo"],
    ["szkoła", "szkoły", "szkole", "szkołę", "szkołą", "szkole", "szkoło"],
    ["szkoły", "szkół", "szkołom", "szkoły", "szkołami", "szkołach", "szkoły"]),
  n("restauracja", "restaurant", "restaurants", "f", ["placeIn", "placeTo"],
    ["restauracja", "restauracji", "restauracji", "restaurację", "restauracją", "restauracji", "restauracjo"],
    ["restauracje", "restauracji", "restauracjom", "restauracje", "restauracjami", "restauracjach", "restauracje"]),
  n("kuchnia", "kitchen", "kitchens", "f", ["placeIn"],
    ["kuchnia", "kuchni", "kuchni", "kuchnię", "kuchnią", "kuchni", "kuchnio"],
    ["kuchnie", "kuchni", "kuchniom", "kuchnie", "kuchniami", "kuchniach", "kuchnie"]),
  n("praca", "work", "jobs", "f", ["abstract"],
    ["praca", "pracy", "pracy", "pracę", "pracą", "pracy", "praco"],
    ["prace", "prac", "pracom", "prace", "pracami", "pracach", "prace"],
    { mass: true }),
  n("ulica", "street", "streets", "f", ["placeIn"],
    ["ulica", "ulicy", "ulicy", "ulicę", "ulicą", "ulicy", "ulico"],
    ["ulice", "ulic", "ulicom", "ulice", "ulicami", "ulicach", "ulice"]),
  n("noc", "night", "nights", "f", ["abstract"],
    ["noc", "nocy", "nocy", "noc", "nocą", "nocy", "nocy"],
    ["noce", "nocy", "nocom", "noce", "nocami", "nocach", "noce"]),
  n("rzecz", "thing", "things", "f", ["object", "abstract"],
    ["rzecz", "rzeczy", "rzeczy", "rzecz", "rzeczą", "rzeczy", "rzeczy"],
    ["rzeczy", "rzeczy", "rzeczom", "rzeczy", "rzeczami", "rzeczach", "rzeczy"]),
  n("miłość", "love", "loves", "f", ["abstract"],
    ["miłość", "miłości", "miłości", "miłość", "miłością", "miłości", "miłości"],
    ["miłości", "miłości", "miłościom", "miłości", "miłościami", "miłościach", "miłości"],
    { mass: true }),
  n("muzyka", "music", "musics", "f", ["abstract"],
    ["muzyka", "muzyki", "muzyce", "muzykę", "muzyką", "muzyce", "muzyko"],
    undefined,
    { mass: true, noPlural: true }),
  n("ręka", "hand", "hands", "f", ["object"],
    ["ręka", "ręki", "ręce", "rękę", "ręką", "ręce", "ręko"],
    ["ręce", "rąk", "rękom", "ręce", "rękami", "rękach", "ręce"],
    { alt: { "pl.ins": ["rękoma"] } }),
  n("wieś", "village", "villages", "f", ["placeTo"],
    ["wieś", "wsi", "wsi", "wieś", "wsią", "wsi", "wsi"],
    ["wsie", "wsi", "wsiom", "wsie", "wsiami", "wsiach", "wsie"]),

  // ---- neuter ------------------------------------------------------------
  n("okno", "window", "windows", "n", ["object"],
    ["okno", "okna", "oknu", "okno", "oknem", "oknie", "okno"],
    ["okna", "okien", "oknom", "okna", "oknami", "oknach", "okna"]),
  n("biurko", "desk", "desks", "n", ["object", "surface"],
    ["biurko", "biurka", "biurku", "biurko", "biurkiem", "biurku", "biurko"],
    ["biurka", "biurek", "biurkom", "biurka", "biurkami", "biurkach", "biurka"]),
  n("dziecko", "child", "children", "n", ["person"],
    ["dziecko", "dziecka", "dziecku", "dziecko", "dzieckiem", "dziecku", "dziecko"],
    ["dzieci", "dzieci", "dzieciom", "dzieci", "dziećmi", "dzieciach", "dzieci"]),
  n("miasto", "city", "cities", "n", ["placeIn", "placeTo"],
    ["miasto", "miasta", "miastu", "miasto", "miastem", "mieście", "miasto"],
    ["miasta", "miast", "miastom", "miasta", "miastami", "miastach", "miasta"]),
  n("muzeum", "museum", "museums", "n", ["placeIn", "placeTo"],
    ["muzeum", "muzeum", "muzeum", "muzeum", "muzeum", "muzeum", "muzeum"],
    ["muzea", "muzeów", "muzeom", "muzea", "muzeami", "muzeach", "muzea"]),
  n("mieszkanie", "flat", "flats", "n", ["placeIn", "placeTo"],
    ["mieszkanie", "mieszkania", "mieszkaniu", "mieszkanie", "mieszkaniem", "mieszkaniu", "mieszkanie"],
    ["mieszkania", "mieszkań", "mieszkaniom", "mieszkania", "mieszkaniami", "mieszkaniach", "mieszkania"]),
  n("jabłko", "apple", "apples", "n", ["food"],
    ["jabłko", "jabłka", "jabłku", "jabłko", "jabłkiem", "jabłku", "jabłko"],
    ["jabłka", "jabłek", "jabłkom", "jabłka", "jabłkami", "jabłkach", "jabłka"]),
  n("mleko", "milk", "milks", "n", ["drink"],
    ["mleko", "mleka", "mleku", "mleko", "mlekiem", "mleku", "mleko"],
    undefined,
    { mass: true, noPlural: true }),
  n("piwo", "beer", "beers", "n", ["drink"],
    ["piwo", "piwa", "piwu", "piwo", "piwem", "piwie", "piwo"],
    ["piwa", "piw", "piwom", "piwa", "piwami", "piwach", "piwa"]),
  n("morze", "sea", "seas", "n", ["placeTo"],
    ["morze", "morza", "morzu", "morze", "morzem", "morzu", "morze"],
    ["morza", "mórz", "morzom", "morza", "morzami", "morzach", "morza"]),
  n("jezioro", "lake", "lakes", "n", ["placeTo"],
    ["jezioro", "jeziora", "jezioru", "jezioro", "jeziorem", "jeziorze", "jezioro"],
    ["jeziora", "jezior", "jeziorom", "jeziora", "jeziorami", "jeziorach", "jeziora"]),
  n("pole", "field", "fields", "n", ["placeTo"],
    ["pole", "pola", "polu", "pole", "polem", "polu", "pole"],
    ["pola", "pól", "polom", "pola", "polami", "polach", "pola"]),
  n("drzewo", "tree", "trees", "n", ["object"],
    ["drzewo", "drzewa", "drzewu", "drzewo", "drzewem", "drzewie", "drzewo"],
    ["drzewa", "drzew", "drzewom", "drzewa", "drzewami", "drzewach", "drzewa"]),
  n("serce", "heart", "hearts", "n", ["object", "abstract"],
    ["serce", "serca", "sercu", "serce", "sercem", "sercu", "serce"],
    ["serca", "serc", "sercom", "serca", "sercami", "sercach", "serca"]),
  n("imię", "name", "names", "n", ["abstract"],
    ["imię", "imienia", "imieniu", "imię", "imieniem", "imieniu", "imię"],
    ["imiona", "imion", "imionom", "imiona", "imionami", "imionach", "imiona"]),
  n("zwierzę", "animal", "animals", "n", ["animal"],
    ["zwierzę", "zwierzęcia", "zwierzęciu", "zwierzę", "zwierzęciem", "zwierzęciu", "zwierzę"],
    ["zwierzęta", "zwierząt", "zwierzętom", "zwierzęta", "zwierzętami", "zwierzętach", "zwierzęta"]),
  n("oko", "eye", "eyes", "n", ["object"],
    ["oko", "oka", "oku", "oko", "okiem", "oku", "oko"],
    ["oczy", "oczu", "oczom", "oczy", "oczami", "oczach", "oczy"],
    { alt: { "pl.ins": ["oczyma"] } }),
];

export function nounsWithTag(tags: Tag[]): Noun[] {
  return NOUNS.filter((noun) => noun.tags.some((t) => tags.includes(t)));
}
