import type { Template } from "./types";

/**
 * {NP} is the noun-phrase slot in the Polish sentence — never put it first,
 * so sentence capitalisation stays fixed.
 * {z} and {w} are prepositions that grow an -e before consonant clusters
 * (z psem, but ze starym psem); resolvePrep in generate.ts handles them.
 * English uses {np} (a/an/some), {npDef} (the) or {npBare} (no article).
 */
export const TEMPLATES: Template[] = [
  // ---- nominative --------------------------------------------------------
  { case: "nom", number: "sg", pl: "To jest {NP}.", en: "This is {np}.",
    requires: [], note: "After 'to jest' the noun stays in the nominative." },
  { case: "nom", number: "pl", pl: "To są {NP}.", en: "These are {np}.",
    requires: [], note: "After 'to są' the noun stays in the nominative." },
  { case: "nom", number: "sg", pl: "Czy to jest {NP}?", en: "Is this {np}?",
    requires: [], note: "After 'to jest' the noun stays in the nominative." },
  { case: "nom", number: "pl", pl: "Czy to są {NP}?", en: "Are these {np}?",
    requires: [], note: "After 'to są' the noun stays in the nominative." },
  { case: "nom", number: "sg", pl: "Tam jest {NP}.", en: "Over there is {np}.",
    requires: [], note: "The subject of the sentence is nominative." },
  { case: "nom", number: "pl", pl: "Tam są {NP}.", en: "Over there are {np}.",
    requires: [], note: "The subject of the sentence is nominative." },
  { case: "nom", number: "sg", pl: "Gdzie jest {NP}?", en: "Where is {npDef}?",
    requires: [], note: "The subject of the sentence is nominative." },
  { case: "nom", number: "pl", pl: "Gdzie są {NP}?", en: "Where are {npDef}?",
    requires: [], note: "The subject of the sentence is nominative." },
  { case: "nom", number: "sg", pl: "Na zdjęciu jest {NP}.", en: "In the photo there is {np}.",
    requires: [], note: "The subject of the sentence is nominative." },
  { case: "nom", number: "pl", pl: "Na zdjęciu są {NP}.", en: "In the photo there are {np}.",
    requires: [], note: "The subject of the sentence is nominative." },
  { case: "nom", number: "sg", pl: "Podoba mi się {NP}.", en: "I like {npDef}.",
    requires: [], note: "With 'podobać się' the thing you like is the subject — nominative." },
  { case: "nom", number: "pl", pl: "Podobają mi się {NP}.", en: "I like {npDef}.",
    requires: [], note: "With 'podobać się' the thing you like is the subject — nominative." },
  { case: "nom", number: "sg", pl: "Interesuje mnie {NP}.", en: "{npDef} interests me.",
    requires: ["abstract", "text", "object"], note: "The subject of the sentence is nominative." },
  { case: "nom", number: "pl", pl: "Interesują mnie {NP}.", en: "{npDef} interest me.",
    requires: ["abstract", "text", "object"], note: "The subject of the sentence is nominative." },

  // everyday phrases
  { case: "nom", number: "sg", pl: "Ile kosztuje {NP}?", en: "How much does {npDef} cost?",
    requires: ["object", "food", "drink", "vehicle", "text"], note: "The subject of the sentence is nominative." },
  { case: "nom", number: "pl", pl: "Ile kosztują {NP}?", en: "How much do {npDef} cost?",
    requires: ["object", "food", "drink", "vehicle", "text"], note: "The subject of the sentence is nominative." },
  { case: "nom", number: "sg", pl: "Zaraz przyjdzie {NP}.", en: "{npDef} is coming in a minute.",
    requires: ["person"], note: "The subject of the sentence is nominative." },
  { case: "nom", number: "pl", pl: "Zaraz przyjdą {NP}.", en: "{npDef} are coming in a minute.",
    requires: ["person"], note: "The subject of the sentence is nominative." },
  { case: "nom", number: "sg", pl: "Czeka na ciebie {NP}.", en: "{npDef} is waiting for you.",
    requires: ["person"], note: "The subject of the sentence is nominative." },
  { case: "nom", number: "sg", pl: "Na stole leży {NP}.", en: "There's {np} on the table.",
    requires: ["text", "food"], note: "The subject of the sentence is nominative." },
  { case: "nom", number: "pl", pl: "Na stole leżą {NP}.", en: "There are {np} on the table.",
    requires: ["text", "food"], note: "The subject of the sentence is nominative." },

  // ---- genitive ----------------------------------------------------------
  { case: "gen", number: "any", pl: "Nie mam {NP}.", en: "I don't have {np}.",
    requires: [], note: "A negated verb turns its accusative object into the genitive." },
  { case: "gen", number: "any", pl: "Nie lubię {NP}.", en: "I don't like {np}.",
    requires: [], note: "A negated verb turns its accusative object into the genitive." },
  { case: "gen", number: "any", pl: "Szukam {NP}.", en: "I'm looking for {np}.",
    requires: [], note: "'szukać' always takes the genitive." },
  { case: "gen", number: "any", pl: "Idę do {NP}.", en: "I'm going to {npDef}.",
    requires: ["placeTo"], note: "'do' (to) always takes the genitive." },
  { case: "gen", number: "any", pl: "Boję się {NP}.", en: "I'm afraid of {np}.",
    requires: ["animal", "person", "abstract"], note: "'bać się' always takes the genitive." },
  { case: "gen", number: "any", pl: "Używam {NP}.", en: "I use {npDef}.",
    requires: ["object", "vehicle"], note: "'używać' always takes the genitive." },
  { case: "gen", number: "any", pl: "Słucham {NP}.", en: "I'm listening to {npDef}.",
    requires: ["abstract", "person", "text"], note: "'słuchać' always takes the genitive." },
  { case: "gen", number: "sg", pl: "To jest samochód {NP}.", en: "This is {npDef}'s car.",
    requires: ["person"], note: "Possession is expressed with the genitive." },
  { case: "gen", number: "sg", pl: "Napiję się {NP}.", en: "I'll have some {npBare}.",
    requires: ["drink"], note: "A partitive amount ('some of') takes the genitive." },
  { case: "gen", number: "any", pl: "Uczę się od {NP}.", en: "I learn from {npDef}.",
    requires: ["person"], note: "'od' (from) always takes the genitive." },
  { case: "gen", number: "sg", pl: "Jestem u {NP}.", en: "I'm at {npDef}'s place.",
    requires: ["person"], note: "'u' (at someone's) always takes the genitive." },

  // everyday phrases
  { case: "gen", number: "any", pl: "Nie ma {NP}.", en: "There is no {npBare}.",
    enPl: "There are no {npBare}.", requires: [],
    note: "'nie ma' (there isn't) always takes the genitive." },
  { case: "gen", number: "sg", pl: "Nie ma tu {NP}.", en: "{npDef} isn't here.",
    requires: ["person", "animal", "object"], note: "'nie ma' (there isn't) always takes the genitive." },
  { case: "gen", number: "any", pl: "Potrzebuję {NP}.", en: "I need {np}.",
    requires: [], note: "'potrzebować' always takes the genitive." },
  { case: "gen", number: "any", pl: "To zależy od {NP}.", en: "It depends on {npDef}.",
    requires: ["person", "abstract"], note: "'od' (from/on) always takes the genitive." },
  { case: "gen", number: "any", pl: "Wracam {z} {NP}.", en: "I'm coming back from {npDef}.",
    requires: ["placeIn"], note: "'z' meaning 'out of / from' takes the genitive." },

  // ---- dative ------------------------------------------------------------
  { case: "dat", number: "any", pl: "Pomagam {NP}.", en: "I help {npDef}.",
    requires: ["person", "animal"], note: "'pomagać' always takes the dative." },
  { case: "dat", number: "any", pl: "Ufam {NP}.", en: "I trust {npDef}.",
    requires: ["person", "animal"], note: "'ufać' always takes the dative." },
  { case: "dat", number: "any", pl: "Daję prezent {NP}.", en: "I'm giving a present to {npDef}.",
    requires: ["person"], note: "The indirect object (the receiver) takes the dative." },
  { case: "dat", number: "any", pl: "Dziękuję {NP} za pomoc.", en: "I thank {npDef} for the help.",
    requires: ["person"], note: "'dziękować' always takes the dative." },
  { case: "dat", number: "any", pl: "Opowiadam bajkę {NP}.", en: "I'm telling a fairy tale to {npDef}.",
    requires: ["person"], note: "The indirect object (the receiver) takes the dative." },
  { case: "dat", number: "any", pl: "Kupuję kwiaty {NP}.", en: "I'm buying flowers for {npDef}.",
    requires: ["person"], note: "The beneficiary of the action takes the dative." },
  { case: "dat", number: "any", pl: "Przyglądam się {NP}.", en: "I'm looking closely at {npDef}.",
    requires: [], note: "'przyglądać się' always takes the dative." },
  { case: "dat", number: "any", pl: "Robię zdjęcie {NP}.", en: "I'm taking a photo of {npDef}.",
    requires: ["person", "animal"], note: "The person the action is done for takes the dative." },
  { case: "dat", number: "any", pl: "Przeszkadzam {NP}.", en: "I'm disturbing {npDef}.",
    requires: ["person"], note: "'przeszkadzać' always takes the dative." },
  { case: "dat", number: "any", pl: "Ten prezent podoba się {NP}.", en: "{npDef} likes this present.",
    enPl: "{npDef} like this present.", requires: ["person"], note: "With 'podobać się' the person who likes takes the dative." },

  // everyday phrases
  { case: "dat", number: "any", pl: "Powiedz to {NP}.", en: "Tell that to {npDef}.",
    requires: ["person"], note: "The receiver of the message takes the dative." },
  { case: "dat", number: "any", pl: "Wysyłam wiadomość {NP}.", en: "I'm sending a message to {npDef}.",
    requires: ["person"], note: "The indirect object (the receiver) takes the dative." },
  { case: "dat", number: "any", pl: "Życzę {NP} miłego dnia.", en: "I wish {npDef} a nice day.",
    requires: ["person"], note: "'życzyć' always takes the dative." },
  { case: "dat", number: "any", pl: "Dzięki {NP} wszystko się udało.", en: "Thanks to {npDef} everything worked out.",
    requires: ["person"], note: "'dzięki' (thanks to) always takes the dative." },

  // ---- accusative --------------------------------------------------------
  { case: "acc", number: "any", pl: "Mam {NP}.", en: "I have {np}.",
    requires: [], note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Widzę {NP}.", en: "I see {np}.",
    requires: [], note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Lubię {NP}.", en: "I like {np}.",
    requires: [], note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Kupuję {NP}.", en: "I'm buying {np}.",
    requires: ["object", "food", "drink", "text", "vehicle"],
    note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Jem {NP}.", en: "I'm eating {np}.",
    requires: ["food"], note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "sg", pl: "Piję {NP}.", en: "I'm drinking {np}.",
    requires: ["drink"], note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Znam {NP}.", en: "I know {npDef}.",
    requires: ["person"], note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Czytam {NP}.", en: "I'm reading {npDef}.",
    requires: ["text"], note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Kocham {NP}.", en: "I love {npDef}.",
    requires: ["person", "animal", "abstract"], note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Zapraszam {NP} na kawę.", en: "I'm inviting {npDef} for a coffee.",
    requires: ["person"], note: "The direct object of a positive verb takes the accusative." },

  // everyday phrases
  { case: "acc", number: "any", pl: "Poproszę {NP}.", en: "{np}, please.",
    requires: ["food", "drink", "text"],
    note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Masz {NP}?", en: "Do you have {np}?",
    requires: [], note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Muszę kupić {NP}.", en: "I have to buy {np}.",
    requires: ["object", "food", "drink", "text", "vehicle"],
    note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Czekam na {NP}.", en: "I'm waiting for {npDef}.",
    requires: ["person", "vehicle"], note: "'na' meaning 'waiting for' takes the accusative." },
  { case: "acc", number: "any", pl: "Mam ochotę na {NP}.", en: "I feel like having {np}.",
    requires: ["food", "drink"], note: "'mieć ochotę na' (to fancy) takes the accusative." },
  { case: "acc", number: "any", pl: "Dzięki za {NP}.", en: "Thanks for {npDef}.",
    requires: ["object", "text", "food", "drink", "abstract"],
    note: "'za' (for) takes the accusative." },

  // ---- instrumental ------------------------------------------------------
  { case: "ins", number: "any", pl: "Interesuję się {NP}.", en: "I'm interested in {np}.",
    requires: ["abstract", "text", "object"], note: "'interesować się' always takes the instrumental." },
  { case: "ins", number: "any", pl: "Zajmuję się {NP}.", en: "I deal with {np}.",
    requires: ["abstract", "text"], note: "'zajmować się' always takes the instrumental." },
  { case: "ins", number: "any", pl: "Rozmawiam {z} {NP}.", en: "I'm talking with {npDef}.",
    requires: ["person"], note: "'z' meaning 'together with' takes the instrumental." },
  { case: "ins", number: "any", pl: "Spotykam się {z} {NP}.", en: "I'm meeting {npDef}.",
    requires: ["person"], note: "'z' meaning 'together with' takes the instrumental." },
  { case: "ins", number: "any", pl: "Idę do kina {z} {NP}.", en: "I'm going to the cinema with {npDef}.",
    requires: ["person"], note: "'z' meaning 'together with' takes the instrumental." },
  { case: "ins", number: "sg", pl: "Jadę {NP}.", en: "I'm travelling by {npBare}.",
    requires: ["vehicle"], note: "The means of transport takes the bare instrumental." },
  { case: "ins", number: "sg", pl: "On jest {NP}.", en: "He is {np}.",
    requires: ["profession"], note: "A profession after 'być' takes the instrumental." },
  { case: "ins", number: "pl", pl: "Oni są {NP}.", en: "They are {np}.",
    requires: ["profession"], note: "A profession after 'być' takes the instrumental." },
  { case: "ins", number: "any", pl: "Obraz wisi nad {NP}.", en: "The picture hangs above {npDef}.",
    requires: ["surface"], note: "'nad' (above) takes the instrumental." },
  { case: "ins", number: "any", pl: "Kot śpi pod {NP}.", en: "The cat sleeps under {npDef}.",
    requires: ["surface"], note: "'pod' (under) takes the instrumental when there is no movement." },
  { case: "ins", number: "any", pl: "Opiekuję się {NP}.", en: "I take care of {npDef}.",
    requires: ["person", "animal"], note: "'opiekować się' always takes the instrumental." },

  // everyday phrases
  { case: "ins", number: "any", pl: "Mieszkam {z} {NP}.", en: "I live with {npDef}.",
    requires: ["person"], note: "'z' meaning 'together with' takes the instrumental." },
  { case: "ins", number: "any", pl: "Spotkajmy się przed {NP}.", en: "Let's meet in front of {npDef}.",
    requires: ["placeIn"], excludeLemmas: ["kuchnia", "pokój", "ulica"], note: "'przed' (in front of) takes the instrumental." },
  { case: "ins", number: "any", pl: "Coś jest nie tak {z} {NP}.", en: "Something is wrong with {npDef}.",
    requires: ["object", "vehicle"], note: "'z' meaning 'with' takes the instrumental." },
  { case: "ins", number: "any", pl: "Pracuję nad {NP}.", en: "I'm working on {npDef}.",
    requires: ["text"], note: "'nad' meaning 'on (a task)' takes the instrumental." },

  // ---- locative ----------------------------------------------------------
  { case: "loc", number: "any", pl: "Myślę o {NP}.", en: "I'm thinking about {npDef}.",
    requires: [], note: "'o' meaning 'about' takes the locative." },
  { case: "loc", number: "any", pl: "Rozmawiamy o {NP}.", en: "We're talking about {npDef}.",
    requires: [], note: "'o' meaning 'about' takes the locative." },
  { case: "loc", number: "any", pl: "Piszę o {NP}.", en: "I'm writing about {npDef}.",
    requires: [], note: "'o' meaning 'about' takes the locative." },
  { case: "loc", number: "any", pl: "Opowiadam o {NP}.", en: "I'm telling a story about {npDef}.",
    requires: [], note: "'o' meaning 'about' takes the locative." },
  { case: "loc", number: "any", pl: "Marzę o {NP}.", en: "I dream about {np}.",
    requires: ["abstract", "object", "placeTo", "vehicle"], note: "'o' meaning 'about' takes the locative." },
  { case: "loc", number: "any", pl: "Mieszkam {w} {NP}.", en: "I live in {npDef}.",
    requires: ["placeIn"], excludeLemmas: ["ulica"], note: "'w' meaning 'inside' takes the locative." },
  { case: "loc", number: "any", pl: "Jestem {w} {NP}.", en: "I'm in {npDef}.",
    requires: ["placeIn"], excludeLemmas: ["ulica"], note: "'w' meaning 'inside' takes the locative." },
  { case: "loc", number: "any", pl: "Byłem wczoraj {w} {NP}.", en: "I was in {npDef} yesterday.",
    requires: ["placeIn"], excludeLemmas: ["ulica"], note: "'w' meaning 'inside' takes the locative." },
  { case: "loc", number: "any", pl: "Książka leży na {NP}.", en: "The book is lying on {npDef}.",
    requires: ["surface"], note: "'na' meaning 'on' takes the locative when there is no movement." },
  { case: "loc", number: "any", pl: "Przy {NP} stoi krzesło.", en: "There is a chair next to {npDef}.",
    requires: ["surface"], note: "'przy' (next to) always takes the locative." },

  // everyday phrases
  { case: "loc", number: "any", pl: "Pracuję {w} {NP}.", en: "I work in {npDef}.",
    requires: ["placeIn"], excludeLemmas: ["ulica"], note: "'w' meaning 'inside' takes the locative." },
  { case: "loc", number: "any", pl: "Spotkajmy się {w} {NP}.", en: "Let's meet in {npDef}.",
    requires: ["placeIn"], excludeLemmas: ["ulica"], note: "'w' meaning 'inside' takes the locative." },
  { case: "loc", number: "any", pl: "Co wiesz o {NP}?", en: "What do you know about {npDef}?",
    requires: [], note: "'o' meaning 'about' takes the locative." },
  { case: "loc", number: "any", pl: "Zależy mi na {NP}.", en: "I care about {npDef}.",
    requires: ["person", "abstract"], note: "'na' after 'zależeć' takes the locative." },
  { case: "loc", number: "any", pl: "Znam się na {NP}.", en: "I know a lot about {npDef}.",
    requires: ["abstract", "text", "object"], note: "'na' after 'znać się' takes the locative." },

  // ---- vocative ----------------------------------------------------------
  { case: "voc", number: "any", pl: "Dzień dobry, {NP}!", en: "Good morning, {npBare}!",
    requires: ["person"], note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "any", pl: "Cześć, {NP}!", en: "Hi, {npBare}!",
    requires: ["person"], note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "any", pl: "Dziękuję, {NP}.", en: "Thank you, {npBare}.",
    requires: ["person"], note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "sg", pl: "Chodź tutaj, {NP}!", en: "Come here, {npBare}!",
    requires: ["person", "animal"], note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "pl", pl: "Chodźcie tutaj, {NP}!", en: "Come here, {npBare}!",
    requires: ["person", "animal"], note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "any", pl: "Przepraszam, {NP}.", en: "Excuse me, {npBare}.",
    requires: ["person"], note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "any", pl: "Dobranoc, {NP}.", en: "Good night, {npBare}.",
    requires: ["person"], note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "sg", pl: "Kocham cię, {NP}.", en: "I love you, {npBare}.",
    requires: ["person"], note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "sg", pl: "Gdzie jesteś, {NP}?", en: "Where are you, {npBare}?",
    requires: ["person", "animal"], note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "pl", pl: "Gdzie jesteście, {NP}?", en: "Where are you, {npBare}?",
    requires: ["person", "animal"], note: "Addressing someone directly takes the vocative." },
  // everyday phrases
  { case: "voc", number: "sg", pl: "Uważaj, {NP}!", en: "Watch out, {npBare}!",
    requires: ["person", "animal"], note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "any", pl: "Do zobaczenia, {NP}!", en: "See you, {npBare}!",
    requires: ["person"], note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "sg", pl: "Nie martw się, {NP}.", en: "Don't worry, {npBare}.",
    requires: ["person"], note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "any", pl: "Miłego dnia, {NP}!", en: "Have a nice day, {npBare}!",
    requires: ["person"], note: "Addressing someone directly takes the vocative." },
];
