import { NOUNS } from "./nouns";
import type { Tag, Template } from "./types";

/**
 * {NP} is the noun-phrase slot in the Polish sentence — never put it first,
 * so sentence capitalisation stays fixed.
 * {z} and {w} are prepositions that grow an -e before consonant clusters
 * (z psem, but ze starym psem); resolvePrep in generate.ts handles them.
 * English uses {np} (a/an/some), {npDef} (the) or {npBare} (no article).
 *
 * Every sentence names the nouns it suits (requires / lemmas); only the
 * "to jest" frames are open to anything. A sentence a Pole would never say
 * ("Gdzie jest noc?", "Kocham chorego psa") is worse than no sentence.
 */

/** Things you can see, point at or find lying around. */
const TANGIBLE: Tag[] = ["person", "animal", "object", "vehicle", "text", "food", "drink"];
/** Relatives need a possessive in English: "This is a husband" is no sentence. */
const RELATIVES = NOUNS.filter((n) => n.tags.includes("family")).map((n) => n.lemma);
/** People you'd call by name: close family and friends. */
const CLOSE: Tag[] = ["family", "friend"];
/** Never addressed this way: "matko" / "ojcze" are church Polish, "żono" / "mężu" archaic. */
const NO_VOCATIVE = ["matka", "ojciec", "żona", "mąż", "rodzina"];
/** The only adjective that sits naturally in a greeting: "kochana babciu". */
const DEAR = ["kochany"];
/** Places you work in: "Pracuję w banku". */
const WORKPLACES = ["sklep", "hotel", "restauracja", "szkoła", "muzeum", "bank", "apteka", "biuro", "kino", "kawiarnia"];
/** Somewhere to meet up. */
const MEETING_PLACES = ["kino", "restauracja", "kawiarnia", "park", "hotel", "muzeum", "sklep", "szkoła", "kościół", "bank"];

export const TEMPLATES: Template[] = [
  // ---- nominative --------------------------------------------------------
  { case: "nom", number: "sg", pl: "To jest {NP}.", en: "This is {np}.",
    requires: [], states: true, excludeLemmas: RELATIVES, note: "After 'to jest' the noun stays in the nominative." },
  { case: "nom", number: "pl", pl: "To są {NP}.", en: "These are {np}.",
    requires: [], states: true, excludeLemmas: RELATIVES, note: "After 'to są' the noun stays in the nominative." },
  { case: "nom", number: "sg", pl: "Czy to jest {NP}?", en: "Is this {np}?",
    requires: [], excludeLemmas: RELATIVES, note: "After 'to jest' the noun stays in the nominative." },
  { case: "nom", number: "pl", pl: "Czy to są {NP}?", en: "Are these {np}?",
    requires: [], excludeLemmas: RELATIVES, note: "After 'to są' the noun stays in the nominative." },
  { case: "nom", number: "sg", pl: "Tam jest {NP}.", en: "Over there is {np}.",
    requires: [...TANGIBLE, "placeIn", "plant"], states: true,
    excludeLemmas: [...RELATIVES, "list", "kuchnia", "pokój"],
    note: "The subject of the sentence is nominative." },
  { case: "nom", number: "pl", pl: "Tam są {NP}.", en: "Over there are {np}.",
    requires: [...TANGIBLE, "placeIn", "plant"], states: true,
    excludeLemmas: [...RELATIVES, "list", "kuchnia", "pokój"],
    note: "The subject of the sentence is nominative." },
  { case: "nom", number: "sg", pl: "Gdzie jest {NP}?", en: "Where is {npDef}?",
    requires: ["person", "animal", "object", "vehicle", "text", "food", "drink", "placeIn"],
    excludeLemmas: ["rodzina", "stół", "łóżko", "biurko", "kwiat", "prezent", "dom", "mieszkanie", "słoń", "koń"],
    note: "The subject of the sentence is nominative." },
  { case: "nom", number: "pl", pl: "Gdzie są {NP}?", en: "Where are {npDef}?",
    requires: ["person", "animal", "object", "vehicle", "text", "food", "drink"],
    excludeLemmas: ["stół", "łóżko", "biurko", "kwiat", "samolot"],
    note: "The subject of the sentence is nominative." },
  { case: "nom", number: "sg", pl: "Na zdjęciu jest {NP}.", en: "In the photo there is {np}.",
    requires: ["person", "animal", "vehicle", "placeIn", "placeTo", "water", "plant", "food"],
    states: true, excludeLemmas: [...RELATIVES, "bank", "apteka", "biuro"],
    note: "The subject of the sentence is nominative." },
  { case: "nom", number: "pl", pl: "Na zdjęciu są {NP}.", en: "In the photo there are {np}.",
    requires: ["person", "animal", "vehicle", "placeIn", "placeTo", "water", "plant", "food"],
    states: true, excludeLemmas: [...RELATIVES, "bank", "apteka", "biuro"],
    note: "The subject of the sentence is nominative." },
  { case: "nom", number: "sg", pl: "Podoba mi się {NP}.", en: "I like {npDef}.",
    requires: ["placeIn", "placeTo", "water", "vehicle", "text", "show", "plant"],
    lemmas: ["imię", "praca", "komputer", "telefon", "prezent", "pogoda"],
    excludeLemmas: ["list", "bank", "apteka", "poczta"],
    note: "With 'podobać się' the thing you like is the subject — nominative." },
  { case: "nom", number: "pl", pl: "Podobają mi się {NP}.", en: "I like {npDef}.",
    requires: ["placeIn", "vehicle", "text", "show", "plant"],
    lemmas: ["komputer", "telefon", "prezent"],
    excludeLemmas: ["list", "bank", "apteka", "kuchnia", "pokój"],
    note: "With 'podobać się' the thing you like is the subject — nominative." },
  { case: "nom", number: "sg", pl: "Interesuje mnie {NP}.", en: "I'm interested in {npBare}.",
    requires: ["topic"], note: "With 'interesować' the thing that interests you is the subject — nominative." },
  { case: "nom", number: "pl", pl: "Interesują mnie {NP}.", en: "I'm interested in {npBare}.",
    requires: ["show"], note: "With 'interesować' the things that interest you are the subject — nominative." },

  // everyday phrases
  { case: "nom", number: "sg", pl: "Ile kosztuje {NP}?", en: "How much does {npDef} cost?",
    requires: ["object", "vehicle", "food", "drink"], lemmas: ["książka", "dom", "mieszkanie", "pokój"],
    excludeLemmas: ["klucz", "portfel", "prezent", "obiad", "autobus", "pociąg", "samolot"],
    note: "The subject of the sentence is nominative." },
  { case: "nom", number: "pl", pl: "Ile kosztują {NP}?", en: "How much do {npDef} cost?",
    requires: ["object", "vehicle", "food"], lemmas: ["książka"],
    excludeLemmas: ["klucz", "portfel", "prezent", "obiad", "ciasto", "autobus", "pociąg", "samolot"],
    note: "The subject of the sentence is nominative." },
  { case: "nom", number: "sg", pl: "Zaraz przyjdzie {NP}.", en: "{npDef} is coming in a minute.",
    requires: ["person"], excludeLemmas: ["pan", "pani"],
    note: "The subject of the sentence is nominative." },
  { case: "nom", number: "pl", pl: "Zaraz przyjdą {NP}.", en: "{npDef} are coming in a minute.",
    requires: ["person"], note: "The subject of the sentence is nominative." },
  { case: "nom", number: "sg", pl: "Czeka na ciebie {NP}.", en: "{npDef} is waiting for you.",
    requires: ["person"], excludeLemmas: ["pan", "pani"],
    note: "The subject of the sentence is nominative." },
  { case: "nom", number: "sg", pl: "Na stole leży {NP}.", en: "There's {np} on the table.",
    requires: ["text"], lemmas: ["chleb", "ser", "jabłko", "ciasto", "telefon", "klucz", "portfel", "nóż", "długopis", "bilet"],
    note: "The subject of the sentence is nominative." },
  { case: "nom", number: "pl", pl: "Na stole leżą {NP}.", en: "There are {np} on the table.",
    requires: ["text"], lemmas: ["jabłko", "klucz", "długopis", "bilet", "telefon", "prezent"],
    note: "The subject of the sentence is nominative." },
  { case: "nom", number: "sg", pl: "Dzwoni {NP}.", en: "{npDef} is calling.",
    requires: CLOSE, lemmas: ["szef", "lekarz"], excludeLemmas: ["dziecko", "rodzina"],
    note: "The one who calls is the subject — nominative." },
  { case: "nom", number: "sg", pl: "Boli mnie {NP}.", en: "My {npBare} hurts.",
    requires: ["body"], adjOnly: ["lewy", "prawy"],
    note: "With 'boleć' the part that hurts is the subject — nominative." },
  { case: "nom", number: "pl", pl: "Bolą mnie {NP}.", en: "My {npBare} hurt.",
    requires: ["body"], excludeLemmas: ["serce", "głowa"], adjOnly: [],
    note: "With 'boleć' the parts that hurt are the subject — nominative." },

  // ---- genitive ----------------------------------------------------------
  { case: "gen", number: "sg", pl: "Nie mam {NP}.", en: "I don't have {np}.",
    requires: ["object", "animal", "food", "drink", "family"],
    lemmas: ["czas", "samochód", "rower", "dom", "mieszkanie", "pokój"],
    excludeLemmas: ["matka", "ojciec", "mama", "tata", "rodzina", "babcia", "dziadek", "list", "gazeta", "kwiat", "radio", "pająk", "słoń", "zwierzę", "koń", "stół", "łóżko", "biurko"],
    note: "A negated verb turns its accusative object into the genitive." },
  { case: "gen", number: "pl", pl: "Nie mam {NP}.", en: "I don't have {np}.",
    requires: [], lemmas: ["dziecko", "klucz", "bilet", "jabłko", "brat"],
    note: "A negated verb turns its accusative object into the genitive." },
  { case: "gen", number: "sg", pl: "Nie lubię {NP}.", en: "I don't like {np}.",
    requires: ["drink", "topic"], lemmas: ["chleb", "ser", "ciasto", "praca"],
    adjOnly: ["zimny", "gorący", "mocny", "czarny", "zielony", "biały", "żółty", "słodki", "głośny", "klasyczny"],
    note: "A negated verb turns its accusative object into the genitive." },
  { case: "gen", number: "pl", pl: "Nie lubię {NP}.", en: "I don't like {np}.",
    requires: ["animal", "show", "profession"], lemmas: ["sąsiad", "pająk", "jabłko"],
    excludeLemmas: ["słoń", "koń", "szef"],
    adjOnly: ["głośny", "głupi", "smutny", "długi", "dziki", "duży", "czarny", "drogi"],
    note: "A negated verb turns its accusative object into the genitive." },
  { case: "gen", number: "any", pl: "Szukam {NP}.", en: "I'm looking for {np}.",
    requires: ["object", "animal", "profession", "placeIn"],
    lemmas: ["praca", "samochód", "rower", "książka"],
    excludeLemmas: ["kuchnia", "miasto", "kościół", "stół", "łóżko", "biurko", "kwiat", "radio", "prezent", "pisarz", "student", "słoń", "zwierzę", "dom", "park", "ogród", "szkoła", "muzeum", "kino", "biuro"],
    note: "'szukać' always takes the genitive." },
  { case: "gen", number: "sg", pl: "Idę do {NP}.", en: "I'm going to {npDef}.",
    requires: ["placeTo"], excludeLemmas: ["dom", "mieszkanie", "hotel", "ogród"],
    note: "'do' (to) always takes the genitive." },
  { case: "gen", number: "any", pl: "Jadę do {NP}.", en: "I'm going to see {npDef}.",
    requires: CLOSE, lemmas: ["lekarz", "dentysta"],
    excludeLemmas: ["dziecko", "kolega", "sąsiad", "rodzina"],
    note: "'do' (to) always takes the genitive — with a person it means 'to their place'." },
  { case: "gen", number: "any", pl: "Boję się {NP}.", en: "I'm afraid of {np}.",
    requires: [], lemmas: ["pies", "pająk", "dentysta", "lekarz", "koń", "ptak", "szef"],
    adjOnly: ["duży", "czarny", "dziki", "głośny", "nowy"],
    note: "'bać się' always takes the genitive." },
  { case: "gen", number: "any", pl: "Używam {NP}.", en: "I'm using {npDef}.",
    requires: [], lemmas: ["komputer", "telefon", "nóż", "długopis", "samochód", "rower", "klucz"],
    note: "'używać' always takes the genitive." },
  { case: "gen", number: "sg", pl: "Słucham {NP}.", en: "I'm listening to {npDef}.",
    requires: [], lemmas: ["muzyka", "radio", "nauczyciel", "mama", "tata", "babcia", "dziadek", "szef"],
    note: "'słuchać' always takes the genitive." },
  { case: "gen", number: "sg", pl: "To jest samochód {NP}.", en: "This is {npDef}'s car.",
    requires: ["family", "friend", "profession"],
    excludeLemmas: ["rodzina", "dziecko", "student", "córka", "syn"],
    note: "Possession is expressed with the genitive." },
  { case: "gen", number: "sg", pl: "Napiję się {NP}.", en: "I'll have some {npBare}.",
    requires: ["drink"], note: "A partitive amount ('some of') takes the genitive." },
  { case: "gen", number: "sg", pl: "Jestem u {NP}.", en: "I'm at {npDef}'s.",
    requires: CLOSE, lemmas: ["lekarz", "dentysta"], excludeLemmas: ["rodzina", "dziecko"],
    note: "'u' (at someone's) always takes the genitive." },

  // everyday phrases
  { case: "gen", number: "any", pl: "Nie ma {NP}.", en: "There is no {npBare}.",
    enPl: "There are no {npBare}.", requires: ["food", "drink"],
    lemmas: ["autobus", "pociąg", "pokój", "bilet", "czas", "cukier"],
    excludeLemmas: ["obiad"],
    note: "'nie ma' (there isn't) always takes the genitive." },
  { case: "gen", number: "sg", pl: "Nie ma tu {NP}.", en: "{npDef} isn't here.",
    requires: ["person", "animal"], lemmas: ["klucz", "telefon", "portfel"],
    excludeLemmas: ["pan", "pani", "rodzina", "słoń", "zwierzę", "koń"],
    note: "'nie ma' (there isn't) always takes the genitive." },
  { case: "gen", number: "sg", pl: "Potrzebuję {NP}.", en: "I need {np}.",
    requires: ["object", "profession"],
    lemmas: ["czas", "pomoc", "pokój", "samochód", "mieszkanie", "praca", "woda"],
    excludeLemmas: ["list", "gazeta", "kwiat", "radio", "prezent", "pisarz", "student", "stół", "łóżko"],
    note: "'potrzebować' always takes the genitive." },
  { case: "gen", number: "sg", pl: "To zależy od {NP}.", en: "It depends on {npDef}.",
    requires: [], lemmas: ["pogoda", "szef", "żona", "mąż", "mama"],
    note: "'od' (from/on) always takes the genitive." },
  { case: "gen", number: "sg", pl: "Wracam {z} {NP}.", en: "I'm coming back from {npDef}.",
    requires: ["placeTo"], excludeLemmas: ["dom", "mieszkanie", "ogród", "hotel", "wieś"],
    note: "'z' meaning 'out of / from' takes the genitive." },
  { case: "gen", number: "any", pl: "Dzwonię do {NP}.", en: "I'm calling {npDef}.",
    requires: [...CLOSE, "profession"], states: true,
    excludeLemmas: ["dziecko", "rodzina", "student", "pisarz"],
    note: "'dzwonić do' (to call someone) takes the genitive." },
  { case: "gen", number: "any", pl: "Kupuję prezent dla {NP}.", en: "I'm buying a present for {npDef}.",
    requires: CLOSE, states: true, excludeLemmas: ["rodzina"],
    note: "'dla' (for) always takes the genitive." },
  { case: "gen", number: "sg", pl: "Nie znam {NP}.", en: "I don't know {npDef}.",
    requires: ["profession"], lemmas: ["sąsiad", "mężczyzna", "kobieta", "chłopiec", "dziewczyna", "miasto"],
    note: "A negated verb turns its accusative object into the genitive." },
  { case: "gen", number: "sg", pl: "W lodówce nie ma {NP}.", en: "There's no {npBare} in the fridge.",
    requires: ["food", "drink"], excludeLemmas: ["herbata", "kawa", "chleb", "obiad", "woda"],
    note: "'nie ma' (there isn't) always takes the genitive." },
  { case: "gen", number: "pl", pl: "Mam dużo {NP}.", en: "I have a lot of {npBare}.",
    requires: ["text", "animal", "show"], lemmas: ["klucz", "prezent", "kwiat"],
    excludeLemmas: ["list", "słoń", "koń", "zwierzę", "pająk", "mecz", "koncert"],
    note: "'dużo' (a lot of) takes the genitive plural." },

  // ---- dative ------------------------------------------------------------
  { case: "dat", number: "any", pl: "Pomagam {NP}.", en: "I'm helping {npDef}.",
    requires: ["person"], states: true, excludeLemmas: ["pan", "pani"],
    adjOnly: ["nowy", "starszy", "młodszy", "chory", "mały", "stary"],
    note: "'pomagać' always takes the dative." },
  { case: "dat", number: "any", pl: "Ufam {NP}.", en: "I trust {npDef}.",
    requires: [...CLOSE, "profession"],
    excludeLemmas: ["dziecko", "student", "pisarz"],
    adjOnly: ["dobry", "stary", "najlepszy", "prawdziwy", "starszy", "nowy"],
    note: "'ufać' always takes the dative." },
  { case: "dat", number: "any", pl: "Daję prezent {NP}.", en: "I'm giving a present to {npDef}.",
    requires: CLOSE, states: true, excludeLemmas: ["rodzina"],
    note: "The indirect object (the receiver) takes the dative." },
  { case: "dat", number: "any", pl: "Dziękuję {NP} za pomoc.", en: "I thank {npDef} for the help.",
    requires: ["person"], adjOnly: ["nowy", "miły", "dobry", "młody", "starszy", "młodszy", "najlepszy"],
    note: "'dziękować' always takes the dative." },
  { case: "dat", number: "any", pl: "Czytam bajkę {NP}.", en: "I'm reading a fairy tale to {npDef}.",
    requires: [], lemmas: ["dziecko", "syn", "córka", "chłopiec"], states: true,
    adjOnly: ["mały", "chory", "smutny", "młodszy"],
    note: "The indirect object (the receiver) takes the dative." },
  { case: "dat", number: "sg", pl: "Kupuję kwiaty {NP}.", en: "I'm buying flowers for {npDef}.",
    requires: ["family"], lemmas: ["dziewczyna", "kobieta"], states: true,
    excludeLemmas: ["syn", "brat", "dziecko", "tata", "rodzina", "dziadek"],
    note: "The beneficiary of the action takes the dative." },
  { case: "dat", number: "any", pl: "Przyglądam się {NP}.", en: "I'm looking closely at {npDef}.",
    requires: ["animal", "plant"], lemmas: ["samochód", "dom", "mężczyzna", "kobieta", "chłopiec", "dziewczyna"],
    states: true,
    note: "'przyglądać się' always takes the dative." },
  { case: "dat", number: "any", pl: "Robię zdjęcie {NP}.", en: "I'm taking a photo of {npDef}.",
    requires: [...CLOSE, "animal"], lemmas: ["dziewczyna", "chłopiec"],
    excludeLemmas: ["rodzina", "pająk"],
    note: "The person the action is done for takes the dative." },
  { case: "dat", number: "any", pl: "Nie przeszkadzaj {NP}!", en: "Don't disturb {npDef}!",
    requires: ["person"], states: true, excludeLemmas: ["pan", "pani"],
    note: "'przeszkadzać' always takes the dative." },
  { case: "dat", number: "any", pl: "Ten prezent podoba się {NP}.", en: "{npDef} likes this present.",
    enPl: "{npDef} like this present.", requires: CLOSE, excludeLemmas: ["rodzina"],
    adjOnly: ["mały", "starszy", "młodszy"],
    note: "With 'podobać się' the person who likes takes the dative." },

  // everyday phrases
  { case: "dat", number: "any", pl: "Powiedz to {NP}.", en: "Tell that to {npDef}.",
    requires: ["person"], adjOnly: ["nowy", "starszy", "młodszy", "najlepszy", "dobry"],
    note: "The receiver of the message takes the dative." },
  { case: "dat", number: "any", pl: "Wysyłam wiadomość {NP}.", en: "I'm sending a message to {npDef}.",
    requires: ["person"], excludeLemmas: ["pan", "pani"],
    adjOnly: ["nowy", "starszy", "młodszy", "najlepszy", "dobry"],
    note: "The indirect object (the receiver) takes the dative." },
  { case: "dat", number: "sg", pl: "Życzę {NP} miłego dnia.", en: "I wish {npDef} a nice day.",
    requires: [], lemmas: ["pan", "pani", "sąsiad"],
    note: "'życzyć' always takes the dative." },
  { case: "dat", number: "any", pl: "Dzięki {NP} wszystko się udało.", en: "Thanks to {npDef} everything worked out.",
    requires: ["person"], adjOnly: ["nowy", "starszy", "młodszy", "najlepszy", "dobry"],
    note: "'dzięki' (thanks to) always takes the dative." },
  { case: "dat", number: "any", pl: "Daję jeść {NP}.", en: "I'm feeding {npDef}.",
    requires: [], lemmas: ["kot", "pies", "koń", "ptak", "dziecko"], states: true,
    note: "'dać jeść' (to feed) takes the dative of the one being fed." },
  { case: "dat", number: "any", pl: "Zawsze mówię {NP} prawdę.", en: "I always tell {npDef} the truth.",
    requires: CLOSE, excludeLemmas: ["rodzina"],
    note: "The receiver of the message takes the dative." },

  // ---- accusative --------------------------------------------------------
  { case: "acc", number: "any", pl: "Mam {NP}.", en: "I have {np}.",
    requires: ["animal", "object", "vehicle", "family"],
    lemmas: ["czas", "dom", "mieszkanie"],
    excludeLemmas: ["matka", "ojciec", "mama", "tata", "rodzina", "babcia", "dziadek", "list", "gazeta", "kwiat", "radio", "rzecz", "słoń", "pająk", "zwierzę", "stół", "łóżko", "biurko", "autobus", "pociąg", "samolot"],
    note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Widzę {NP}.", en: "I can see {np}.",
    requires: ["person", "animal", "vehicle", "placeIn", "placeTo", "water", "plant"],
    states: true, excludeLemmas: [...RELATIVES, "kuchnia", "pokój", "bank", "biuro"],
    note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "sg", pl: "Lubię {NP}.", en: "I like {np}.",
    requires: ["drink", "topic"], lemmas: ["chleb", "ser", "ciasto", "praca"],
    note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "pl", pl: "Lubię {NP}.", en: "I like {np}.",
    requires: ["animal", "show", "food"], lemmas: ["książka", "kwiat"],
    excludeLemmas: ["pająk"],
    note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Kupuję {NP}.", en: "I'm buying {np}.",
    requires: ["object", "food", "drink", "vehicle"], lemmas: ["książka", "gazeta", "mieszkanie", "dom"],
    excludeLemmas: ["klucz", "list", "zupa", "obiad"],
    note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Jem {NP}.", en: "I'm eating {np}.",
    requires: ["food"], note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "sg", pl: "Piję {NP}.", en: "I'm drinking {np}.",
    requires: ["drink"], note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Znam {NP}.", en: "I know {npDef}.",
    requires: ["profession", "friend"], lemmas: ["mężczyzna", "kobieta", "chłopiec", "dziewczyna"],
    excludeLemmas: ["student"],
    note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Czytam {NP}.", en: "I'm reading {np}.",
    requires: ["text"], note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Kocham {NP}.", en: "I love {npDef}.",
    requires: ["family"], note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "sg", pl: "Uwielbiam {NP}.", en: "I love {np}.",
    requires: ["topic"], lemmas: ["kawa", "herbata", "wino", "ciasto", "ser"],
    excludeLemmas: ["polityka"],
    note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "pl", pl: "Uwielbiam {NP}.", en: "I love {np}.",
    requires: ["show"], lemmas: ["kot", "pies", "koń", "kwiat", "książka"],
    note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Zapraszam {NP} na kawę.", en: "I'm inviting {npDef} for a coffee.",
    requires: CLOSE, lemmas: ["pani"], excludeLemmas: ["dziecko", "rodzina", "syn", "córka"],
    note: "The direct object of a positive verb takes the accusative." },

  // everyday phrases
  { case: "acc", number: "any", pl: "Poproszę {NP}.", en: "{np}, please.",
    requires: ["food", "drink"], lemmas: ["bilet", "gazeta"],
    note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Masz {NP}?", en: "Do you have {np}?",
    requires: ["object", "animal"], lemmas: ["czas", "brat", "siostra", "dziecko"],
    excludeLemmas: ["stół", "łóżko", "biurko", "list", "gazeta", "kwiat", "radio", "prezent", "słoń", "pająk", "zwierzę", "koń"],
    note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Muszę kupić {NP}.", en: "I have to buy {np}.",
    requires: ["object", "food", "drink"], lemmas: ["bilet", "gazeta", "samochód", "rower"],
    excludeLemmas: ["klucz", "list", "zupa", "obiad"],
    note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Czekam na {NP}.", en: "I'm waiting for {npDef}.",
    requires: [...CLOSE, "show"], lemmas: ["autobus", "pociąg", "obiad", "pogoda", "lekarz", "szef"],
    excludeLemmas: ["rodzina", "serial", "film"],
    adjOnly: ["ostatni", "pierwszy", "nowy", "ważny", "starszy", "młodszy", "najlepszy"],
    note: "'na' meaning 'waiting for' takes the accusative." },
  { case: "acc", number: "any", pl: "Mam ochotę na {NP}.", en: "I feel like having {np}.",
    requires: ["food", "drink"], note: "'mieć ochotę na' (to fancy) takes the accusative." },
  { case: "acc", number: "any", pl: "Dzięki za {NP}.", en: "Thanks for {npDef}.",
    requires: ["food", "drink"], lemmas: ["kwiat", "list", "prezent", "pomoc", "książka", "bilet"],
    note: "'za' (for) takes the accusative." },
  { case: "acc", number: "any", pl: "Oglądam {NP}.", en: "I'm watching {np}.",
    requires: ["show"], note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "sg", pl: "Otwieram {NP}.", en: "I'm opening {npDef}.",
    requires: [], lemmas: ["okno", "list", "piwo", "wino", "sklep", "prezent", "książka"],
    note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "any", pl: "Martwię się o {NP}.", en: "I'm worried about {npDef}.",
    requires: CLOSE, states: true, excludeLemmas: ["rodzina"],
    note: "'martwić się o' (to worry about) takes the accusative." },
  { case: "acc", number: "any", pl: "Odwiedzam {NP}.", en: "I'm visiting {npDef}.",
    requires: CLOSE, states: true, excludeLemmas: ["dziecko", "rodzina"],
    note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "sg", pl: "Jadę nad {NP}.", en: "I'm going to {npDef}.",
    requires: ["water"], note: "'nad' with movement towards water takes the accusative." },
  { case: "acc", number: "sg", pl: "Idę na {NP}.", en: "I'm going to {npDef}.",
    requires: [], lemmas: ["mecz", "koncert", "poczta", "film"],
    note: "'na' with movement towards an event takes the accusative." },
  { case: "acc", number: "any", pl: "Zamawiam {NP}.", en: "I'm ordering {np}.",
    requires: ["food", "drink"], excludeLemmas: ["chleb", "jabłko", "mleko", "woda"],
    note: "The direct object of a positive verb takes the accusative." },
  { case: "acc", number: "sg", pl: "Wynajmuję {NP}.", en: "I'm renting {np}.",
    requires: [], lemmas: ["mieszkanie", "pokój", "samochód", "dom", "rower"],
    note: "The direct object of a positive verb takes the accusative." },

  // ---- instrumental ------------------------------------------------------
  { case: "ins", number: "sg", pl: "Interesuję się {NP}.", en: "I'm interested in {npBare}.",
    requires: ["topic"], note: "'interesować się' always takes the instrumental." },
  { case: "ins", number: "sg", pl: "Zajmuję się {NP}.", en: "I work in {npBare}.",
    requires: [], lemmas: ["polityka", "sztuka", "muzyka", "sport", "historia"],
    adjOnly: [], note: "'zajmować się' always takes the instrumental." },
  { case: "ins", number: "any", pl: "Rozmawiam {z} {NP}.", en: "I'm talking with {npDef}.",
    requires: ["person"], states: true, excludeLemmas: ["rodzina"],
    note: "'z' meaning 'together with' takes the instrumental." },
  { case: "ins", number: "any", pl: "Spotykam się {z} {NP}.", en: "I'm meeting {npDef}.",
    requires: [...CLOSE, "profession"], excludeLemmas: ["dziecko", "dentysta", "student"],
    note: "'z' meaning 'together with' takes the instrumental." },
  { case: "ins", number: "any", pl: "Idę do kina {z} {NP}.", en: "I'm going to the cinema with {npDef}.",
    requires: CLOSE, excludeLemmas: ["rodzina"],
    note: "'z' meaning 'together with' takes the instrumental." },
  { case: "ins", number: "sg", pl: "Jadę {NP}.", en: "I'm taking {npDef}.",
    requires: ["vehicle"], note: "The means of transport takes the bare instrumental." },
  { case: "ins", number: "sg", pl: "On jest {NP}.", en: "He is {np}.",
    requires: ["profession"], adjOnly: ["dobry", "znany", "młody", "nowy", "polski", "mądry"],
    note: "A profession after 'być' takes the instrumental." },
  { case: "ins", number: "pl", pl: "Oni są {NP}.", en: "They are {np}.",
    requires: ["profession"], adjOnly: ["dobry", "znany", "młody", "nowy", "polski", "mądry"],
    note: "A profession after 'być' takes the instrumental." },
  { case: "ins", number: "sg", pl: "Chcę zostać {NP}.", en: "I want to become {np}.",
    requires: ["profession"], excludeLemmas: ["student"],
    adjOnly: ["dobry", "znany"],
    note: "After 'zostać' (to become) a profession takes the instrumental." },
  { case: "ins", number: "sg", pl: "Obraz wisi nad {NP}.", en: "The picture hangs above {npDef}.",
    requires: [], lemmas: ["stół", "łóżko", "biurko", "okno"],
    note: "'nad' (above) takes the instrumental." },
  { case: "ins", number: "sg", pl: "Kot śpi pod {NP}.", en: "The cat sleeps under {npDef}.",
    requires: [], lemmas: ["stół", "łóżko", "biurko", "drzewo"],
    note: "'pod' (under) takes the instrumental when there is no movement." },
  { case: "ins", number: "any", pl: "Opiekuję się {NP}.", en: "I take care of {npDef}.",
    requires: ["family"], lemmas: ["kot", "pies", "koń"], states: true,
    excludeLemmas: ["rodzina"],
    note: "'opiekować się' always takes the instrumental." },

  // everyday phrases
  { case: "ins", number: "sg", pl: "Opiekuję się {NP}.", en: "I look after {npDef}.",
    requires: [], lemmas: ["ogród", "dom", "mieszkanie"], adjOnly: [],
    note: "'opiekować się' always takes the instrumental." },
  { case: "ins", number: "any", pl: "Mieszkam {z} {NP}.", en: "I live with {npDef}.",
    requires: ["family"], lemmas: ["kolega", "przyjaciel", "kot", "pies"],
    excludeLemmas: ["rodzina"],
    note: "'z' meaning 'together with' takes the instrumental." },
  { case: "ins", number: "sg", pl: "Spotkajmy się przed {NP}.", en: "Let's meet in front of {npDef}.",
    requires: [], lemmas: MEETING_PLACES,
    adjOnly: ["nowy", "włoski", "polski"],
    note: "'przed' (in front of) takes the instrumental." },
  { case: "ins", number: "sg", pl: "Coś jest nie tak {z} {NP}.", en: "Something is wrong with {npDef}.",
    requires: [], lemmas: ["komputer", "telefon", "samochód", "rower", "radio"],
    note: "'z' meaning 'with' takes the instrumental." },
  { case: "ins", number: "sg", pl: "Pracuję nad {NP}.", en: "I'm working on {npDef}.",
    requires: [], lemmas: ["książka", "projekt", "film"],
    note: "'nad' meaning 'on (a task)' takes the instrumental." },
  { case: "ins", number: "sg", pl: "Mieszkam nad {NP}.", en: "I live by {npDef}.",
    requires: ["water"], note: "'nad' (by the water) takes the instrumental when there is no movement." },
  { case: "ins", number: "sg", pl: "Poproszę herbatę {z} {NP}.", en: "Tea with {npBare}, please.",
    requires: [], lemmas: ["cytryna", "mleko", "cukier"], adjOnly: [],
    note: "'z' meaning 'with' takes the instrumental." },

  // ---- locative ----------------------------------------------------------
  { case: "loc", number: "any", pl: "Myślę o {NP}.", en: "I'm thinking about {npDef}.",
    requires: [...CLOSE, "animal", "water"], lemmas: ["praca", "tydzień", "samochód", "mieszkanie", "dom"],
    states: true, excludeLemmas: ["pająk", "słoń", "zwierzę"],
    note: "'o' meaning 'about' takes the locative." },
  { case: "loc", number: "any", pl: "Rozmawiamy o {NP}.", en: "We're talking about {npDef}.",
    requires: ["topic", "show", "profession", "friend"], lemmas: ["pogoda", "praca", "książka", "szef"],
    note: "'o' meaning 'about' takes the locative." },
  { case: "loc", number: "sg", pl: "Piszę o {NP}.", en: "I'm writing about {npBare}.",
    requires: ["topic"], lemmas: ["miłość"], note: "'o' meaning 'about' takes the locative." },
  { case: "loc", number: "any", pl: "Opowiadam o {NP}.", en: "I'm telling you about {npDef}.",
    requires: [...CLOSE, "show"], lemmas: ["praca", "miasto", "wieś"],
    note: "'o' meaning 'about' takes the locative." },
  { case: "loc", number: "sg", pl: "Marzę o {NP}.", en: "I dream of {np}.",
    requires: [], lemmas: ["dom", "mieszkanie", "samochód", "rower", "pies", "kot", "praca", "miłość", "koń"],
    note: "'o' meaning 'about' takes the locative." },
  { case: "loc", number: "sg", pl: "Mieszkam {w} {NP}.", en: "I live in {np}.",
    requires: [], lemmas: ["dom", "mieszkanie", "miasto", "hotel"],
    note: "'w' meaning 'inside' takes the locative." },
  { case: "loc", number: "sg", pl: "Jestem {w} {NP}.", en: "I'm in {npDef}.",
    requires: ["placeIn"], excludeLemmas: ["dom"],
    note: "'w' meaning 'inside' takes the locative." },
  { case: "loc", number: "sg", pl: "Byłem wczoraj {w} {NP}.", en: "I was at {npDef} yesterday.",
    requires: ["placeIn"], excludeLemmas: ["kuchnia", "pokój", "mieszkanie", "dom", "ogród", "biuro"],
    note: "'w' meaning 'inside' takes the locative." },
  { case: "loc", number: "sg", pl: "Książka leży na {NP}.", en: "The book is lying on {npDef}.",
    requires: ["surface"], note: "'na' meaning 'on' takes the locative when there is no movement." },
  { case: "loc", number: "sg", pl: "Przy {NP} stoi krzesło.", en: "There is a chair next to {npDef}.",
    requires: [], lemmas: ["stół", "biurko", "okno", "łóżko"],
    note: "'przy' (next to) always takes the locative." },

  // everyday phrases
  { case: "loc", number: "sg", pl: "Pracuję {w} {NP}.", en: "I work at {np}.",
    requires: [], lemmas: WORKPLACES, note: "'w' meaning 'inside' takes the locative." },
  { case: "loc", number: "sg", pl: "Spotkajmy się {w} {NP}.", en: "Let's meet at {npDef}.",
    requires: [], lemmas: MEETING_PLACES, adjOnly: ["nowy", "włoski", "polski"],
    note: "'w' meaning 'inside' takes the locative." },
  { case: "loc", number: "any", pl: "Co wiesz o {NP}?", en: "What do you know about {npDef}?",
    requires: ["topic", "profession"], lemmas: ["miasto", "szef", "sąsiad"],
    adjOnly: ["nowy", "polski", "włoski", "znany", "klasyczny"],
    note: "'o' meaning 'about' takes the locative." },
  { case: "loc", number: "sg", pl: "Zależy mi na {NP}.", en: "I care about {npDef}.",
    requires: ["family"], lemmas: ["praca"], note: "'na' after 'zależeć' takes the locative." },
  { case: "loc", number: "sg", pl: "Znam się na {NP}.", en: "I know a lot about {npBare}.",
    requires: ["topic"], lemmas: ["wino"], note: "'na' after 'znać się' takes the locative." },
  { case: "loc", number: "pl", pl: "Znam się na {NP}.", en: "I know a lot about {npBare}.",
    requires: [], lemmas: ["samochód", "komputer", "koń", "film"], adjOnly: [],
    note: "'na' after 'znać się' takes the locative." },
  { case: "loc", number: "sg", pl: "Mieszkam przy {NP}.", en: "I live next to {npDef}.",
    requires: [], lemmas: ["ulica", "park", "szkoła", "kościół", "morze", "jezioro", "rzeka"],
    note: "'przy' (next to) always takes the locative." },
  { case: "loc", number: "sg", pl: "Jestem na {NP}.", en: "I'm at {npDef}.",
    requires: [], lemmas: ["mecz", "koncert", "poczta"],
    note: "'na' with events (and a few places) takes the locative when there is no movement." },

  // ---- vocative ----------------------------------------------------------
  { case: "voc", number: "any", pl: "Dzień dobry, {NP}!", en: "Good morning, {npBare}!",
    requires: CLOSE, excludeLemmas: NO_VOCATIVE, adjOnly: DEAR,
    note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "any", pl: "Cześć, {NP}!", en: "Hi, {npBare}!",
    requires: CLOSE, excludeLemmas: NO_VOCATIVE, adjOnly: DEAR,
    note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "any", pl: "Dziękuję, {NP}.", en: "Thank you, {npBare}.",
    requires: CLOSE, excludeLemmas: NO_VOCATIVE, adjOnly: DEAR,
    note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "sg", pl: "Chodź tutaj, {NP}!", en: "Come here, {npBare}!",
    requires: ["family"], lemmas: ["chłopiec", "pies", "kot"], excludeLemmas: NO_VOCATIVE,
    adjOnly: DEAR, note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "pl", pl: "Chodźcie tutaj, {NP}!", en: "Come here, {npBare}!",
    requires: [], lemmas: ["dziecko", "chłopiec", "kolega"], adjOnly: [...DEAR, "mały"],
    note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "any", pl: "Przepraszam, {NP}.", en: "Sorry, {npBare}.",
    requires: CLOSE, excludeLemmas: NO_VOCATIVE, adjOnly: DEAR,
    note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "any", pl: "Dobranoc, {NP}.", en: "Good night, {npBare}.",
    requires: ["family"], excludeLemmas: NO_VOCATIVE, adjOnly: DEAR,
    note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "sg", pl: "Kocham cię, {NP}.", en: "I love you, {npBare}.",
    requires: ["family"], excludeLemmas: NO_VOCATIVE, adjOnly: DEAR,
    note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "sg", pl: "Gdzie jesteś, {NP}?", en: "Where are you, {npBare}?",
    requires: ["family"], lemmas: ["pies", "kot"], excludeLemmas: NO_VOCATIVE,
    adjOnly: DEAR, note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "pl", pl: "Gdzie jesteście, {NP}?", en: "Where are you, {npBare}?",
    requires: [], lemmas: ["dziecko", "chłopiec", "kolega"], adjOnly: [...DEAR, "mały"],
    note: "Addressing someone directly takes the vocative." },
  // everyday phrases
  { case: "voc", number: "sg", pl: "Uważaj, {NP}!", en: "Watch out, {npBare}!",
    requires: CLOSE, lemmas: ["chłopiec"], excludeLemmas: NO_VOCATIVE, adjOnly: DEAR,
    note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "any", pl: "Do zobaczenia, {NP}!", en: "See you, {npBare}!",
    requires: CLOSE, excludeLemmas: NO_VOCATIVE, adjOnly: DEAR,
    note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "sg", pl: "Nie martw się, {NP}.", en: "Don't worry, {npBare}.",
    requires: CLOSE, excludeLemmas: NO_VOCATIVE, adjOnly: DEAR,
    note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "any", pl: "Miłego dnia, {NP}!", en: "Have a nice day, {npBare}!",
    requires: CLOSE, excludeLemmas: NO_VOCATIVE, adjOnly: DEAR,
    note: "Addressing someone directly takes the vocative." },
  { case: "voc", number: "any", pl: "Wszystkiego najlepszego, {NP}!", en: "Happy birthday, {npBare}!",
    requires: CLOSE, excludeLemmas: NO_VOCATIVE, adjOnly: DEAR,
    note: "Addressing someone directly takes the vocative." },
];
