import Link from "next/link";
import { ExampleLine, ExampleList, GuideLayout, Pl, PractiseLink, Section, TD, TH, TableBox } from "@/components/Guide";
import { CASE_INFO } from "@/lib/cases";
import { CASE_USES, caseEndingTable, caseExamples, casePracticeHref, caseTriggers, practiceHref } from "@/lib/guides";
import { pageMetadata } from "@/lib/site";
import { CASES } from "@/lib/types";

const PATH = "/polish-cases";

export const metadata = pageMetadata({
  title: "Polish cases explained: endings and examples",
  description:
    "What each of the seven Polish cases does, the prepositions and verbs that trigger it, ending tables for model nouns and example sentences with English, then practise each case.",
  path: PATH,
});

export default function PolishCasesPage() {
  const table = caseEndingTable();
  const examples = caseExamples();
  return (
    <GuideLayout
      path={PATH}
      eyebrow="Grammar guide"
      title="Polish cases: what each one does, and the endings"
      intro={
        <>
          <p>
            A Polish noun changes its ending to show its job in the sentence. There are seven cases. Each
            answers its own question, and most are triggered by a particular preposition or verb, so
            learning a case means learning its endings <em>and</em> what calls for it.
          </p>
          <p>
            Every Polish sentence and form on this page is generated by the same grammar engine as the
            drills, so the endings are the ones the drills check.
          </p>
        </>
      }
    >
      <Section id="overview" title="The seven cases at a glance">
        <TableBox>
          <thead>
            <tr>
              <th className={TH}>Case</th>
              <th className={TH}>Question</th>
              <th className={TH}>Used for</th>
            </tr>
          </thead>
          <tbody>
            {CASES.map((kase) => (
              <tr key={kase}>
                <td className={TD}>
                  <a href={`#${kase}`} className="font-medium text-accent underline underline-offset-4">
                    {CASE_INFO[kase].en}
                  </a>
                  <Pl className="block text-muted">{CASE_INFO[kase].pl}</Pl>
                </td>
                <td className={TD}>
                  <Pl className="whitespace-nowrap">{CASE_INFO[kase].question}</Pl>
                </td>
                <td className={`${TD} min-w-[16rem]`}>{CASE_USES[kase]}</td>
              </tr>
            ))}
          </tbody>
        </TableBox>
      </Section>

      <Section id="endings" title="Case endings: five model nouns">
        <p className="text-muted">
          Polish has three genders, but the masculine splits three ways in the endings: people, animals
          and things. The accusative is where it shows most: a masculine person or animal copies the
          genitive, a masculine thing copies the nominative.
        </p>
        {(["sg", "pl"] as const).map((number) => (
          <TableBox key={number} caption={number === "sg" ? "Singular" : "Plural"}>
            <thead>
              <tr>
                <th className={TH}>Case</th>
                {table.nouns.map((n) => (
                  <th key={n.lemma} className={TH}>
                    <Pl className="text-foreground">{n.lemma}</Pl>
                    <span className="block text-xs font-normal">
                      {n.en} · {n.gender}
                    </span>
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {table.rows.map((row) => (
                <tr key={row.kase}>
                  <td className={`${TD} whitespace-nowrap text-muted`}>{CASE_INFO[row.kase].en}</td>
                  {row[number].map((form, i) => (
                    <td key={i} className={`${TD} sentence text-base`}>
                      <Pl>{form}</Pl>
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </TableBox>
        ))}
      </Section>

      {CASES.map((kase) => {
        const info = CASE_INFO[kase];
        const triggers = caseTriggers(kase);
        return (
          <Section
            key={kase}
            id={kase}
            title={
              <>
                {info.en} <Pl className="font-normal text-muted">({info.pl})</Pl>
              </>
            }
          >
            <p>{CASE_USES[kase]}</p>
            <p className="text-muted">
              Question: <Pl className="font-medium text-foreground">{info.question}</Pl>
            </p>
            <h3 className="text-sm font-semibold uppercase tracking-wide text-muted">When to use it</h3>
            <ul className="space-y-3">
              {triggers.map((t) => (
                <li key={t.note} className="rounded-xl border border-line bg-surface px-4 py-3">
                  <p className="font-medium">{t.note}</p>
                  {t.example ? (
                    <div className="mt-1">
                      <ExampleLine example={t.example} />
                    </div>
                  ) : null}
                </li>
              ))}
            </ul>
            <PractiseLink href={casePracticeHref(kase)}>Practise the {info.en.toLowerCase()}</PractiseLink>
          </Section>
        );
      })}

      <Section id="adjectives" title="Adjectives follow the noun">
        <p className="text-muted">
          An adjective takes the case, number and gender of its noun, so in a real sentence both change
          together. A few mixed examples:
        </p>
        <ExampleList examples={examples} />
        <div className="flex flex-wrap items-center gap-4">
          <PractiseLink
            href={practiceHref({ kind: "cases", cases: [...CASES], numbers: ["sg", "pl"], mode: "both" })}
          >
            Practise all seven cases
          </PractiseLink>
          <Link href="/cases" className="text-accent underline underline-offset-4">
            Choose cases, genders and level
          </Link>
        </div>
      </Section>
    </GuideLayout>
  );
}
