/**
 * npm run icons [-- --keep-svg]
 *
 * Regenerates every app icon from one source, public/brand/icon.svg
 * (plans/phase-3.md §1–§2):
 *
 *   public/icons/icon-192.png      manifest, purpose "any"
 *   public/icons/icon-512.png      manifest, purpose "any"
 *   public/icons/maskable-512.png  manifest, purpose "maskable" (logo in the 80% safe zone)
 *   app/apple-icon.png             180×180, opaque (iOS adds its own corners)
 *   app/favicon.ico                16, 32 and 48 px
 *
 * While the brand is a placeholder, icon.svg is itself generated: a monogram
 * (the first letter of BRAND.name) on the accent colour from app/globals.css.
 * It carries the GENERATED marker below and is rewritten on every run, so a
 * rename in lib/brand.ts only needs `npm run icons`. A real logo replaces the
 * file (without the marker, or run with --keep-svg) and is then used as is.
 *
 * Rendering uses sharp (librsvg), which Next already installs. The monogram is
 * SVG text, so it is drawn with the fonts on the machine running the script
 * (DejaVu Sans / Inter / Arial / any sans-serif); the PNGs are committed.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import sharp from "sharp";
import { BRAND } from "../lib/brand";

const ROOT = join(__dirname, "..");
const SOURCE = join(ROOT, "public", "brand", "icon.svg");
const GENERATED = "generated by scripts/icons.ts from lib/brand.ts";

/** A colour token from the light theme in app/globals.css (the first :root block). */
function cssToken(name: string): string {
  const css = readFileSync(join(ROOT, "app", "globals.css"), "utf8");
  const root = /:root\s*{([^}]*)}/.exec(css)?.[1] ?? "";
  const value = new RegExp(`--${name}:\\s*([^;]+);`).exec(root)?.[1]?.trim();
  if (!value) throw new Error(`app/globals.css: no --${name} in the first :root block`);
  return value;
}

function escapeXml(text: string): string {
  return text.replace(/[&<>"']/g, (c) => `&#${c.charCodeAt(0)};`);
}

/** The placeholder logo: a rounded square in the accent colour with the brand's initial. */
function monogram(letter: string, background: string, foreground: string): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">
  <!-- ${GENERATED}: the placeholder monogram. Replace this file with the real logo and run npm run icons. -->
  <rect width="512" height="512" rx="112" fill="${background}"/>
  <text x="256" y="256" dy="0.35em" text-anchor="middle" font-family="DejaVu Sans, Inter, Arial, Helvetica, sans-serif" font-weight="700" font-size="300" fill="${foreground}">${escapeXml(letter)}</text>
</svg>
`;
}

/** The SVG rendered square at `size`. */
function render(svg: Buffer, size: number): Promise<Buffer> {
  return sharp(svg, { density: Math.max(72, (72 * size) / 512 * 4) })
    .resize(size, size, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png()
    .toBuffer();
}

/** The logo at `scale` of the side, centred on a full-bleed, opaque `background`. */
async function onBackground(svg: Buffer, size: number, scale: number, background: string): Promise<Buffer> {
  const inner = Math.round(size * scale);
  const logo = await render(svg, inner);
  return sharp({ create: { width: size, height: size, channels: 4, background } })
    .composite([{ input: logo, gravity: "centre" }])
    .flatten({ background })
    .png()
    .toBuffer();
}

/** An .ico holding PNG images (supported by every current browser). */
function ico(images: { size: number; png: Buffer }[]): Buffer {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2); // icon
  header.writeUInt16LE(images.length, 4);
  const entries: Buffer[] = [];
  let offset = 6 + 16 * images.length;
  for (const { size, png } of images) {
    const entry = Buffer.alloc(16);
    entry.writeUInt8(size >= 256 ? 0 : size, 0);
    entry.writeUInt8(size >= 256 ? 0 : size, 1);
    entry.writeUInt8(0, 2); // no palette
    entry.writeUInt8(0, 3);
    entry.writeUInt16LE(1, 4); // colour planes
    entry.writeUInt16LE(32, 6); // bits per pixel
    entry.writeUInt32LE(png.length, 8);
    entry.writeUInt32LE(offset, 12);
    offset += png.length;
    entries.push(entry);
  }
  return Buffer.concat([header, ...entries, ...images.map((i) => i.png)]);
}

function write(path: string, data: Buffer | string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, data);
  console.log(`  ${relative(ROOT, path)}`);
}

async function main() {
  const accent = cssToken("accent");
  const keepSvg = process.argv.includes("--keep-svg");
  let existing = "";
  try {
    existing = readFileSync(SOURCE, "utf8");
  } catch {
    // no source yet: generate it
  }

  console.log("icons:");
  if (!keepSvg && (existing === "" || existing.includes(GENERATED))) {
    const letter = [...BRAND.name.trim()][0]?.toLocaleUpperCase("pl") ?? "?";
    write(SOURCE, monogram(letter, accent, "#ffffff"));
  } else {
    console.log(`  ${relative(ROOT, SOURCE)} (kept: not generated)`);
  }

  const svg = readFileSync(SOURCE);
  write(join(ROOT, "public", "icons", "icon-192.png"), await render(svg, 192));
  write(join(ROOT, "public", "icons", "icon-512.png"), await render(svg, 512));
  // maskable: launchers crop to a circle or squircle inside the central 80%
  write(join(ROOT, "public", "icons", "maskable-512.png"), await onBackground(svg, 512, 0.8, accent));
  write(join(ROOT, "app", "apple-icon.png"), await onBackground(svg, 180, 1, accent));
  const favicons = await Promise.all([16, 32, 48].map(async (size) => ({ size, png: await render(svg, size) })));
  write(join(ROOT, "app", "favicon.ico"), ico(favicons));
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
